#!/usr/bin/env python3
"""Assemble content.json: i18n.json + insights articles + homepage focus cards."""
import json

i18n = json.load(open('.scrape/i18n.json', encoding='utf-8'))

# 新增「招商政策」導航頁（build.py PAGES 含 policy，nav 需有對應鍵）
for code, label in {"zh-TW": "招商政策", "zh-CN": "招商政策",
                    "en": "Investment Policies", "pt": "Políticas de Investimento"}.items():
    i18n[code]['nav']['policy'] = label

# 新增「新聞動態」導航頁（build.py PAGES 含 news，nav 需有對應鍵）
for code, label in {"zh-TW": "新聞動態", "zh-CN": "新闻动态",
                    "en": "News", "pt": "Notícias"}.items():
    i18n[code]['nav']['news'] = label

# 招商政策數據（region: macao / hengqin；繁中為母本，其他語言為對應譯文）
policies = [
    {"region": "macao", "year": "2025–2026",
     "title": {"zh-TW": "政府產業基金及科技成果轉化引導基金", "zh-CN": "政府产业基金及科技成果转化引导基金",
               "en": "Government Industrial Fund and Technology Achievement Transformation Guidance Fund",
               "pt": "Fundo Industrial do Governo e Fundo Orientador para a Transformação de Conquistas Científicas"},
     "summary": {"zh-TW": "政府牽頭設立產業基金與科技成果轉化引導基金，以「政府+民間共同投資」模式吸引高新科技企業及項目落戶澳門。",
                 "zh-CN": "政府牵头设立产业基金与科技成果转化引导基金，以「政府+民间共同投资」模式吸引高新科技企业及项目落户澳门。",
                 "en": "Government-led industrial fund and technology transformation guidance fund, attracting high-tech enterprises and projects to Macao through a \"government + private co-investment\" model.",
                 "pt": "Fundo industrial liderado pelo Governo e fundo orientador de transformação tecnológica, atraindo empresas e projetos de alta tecnologia para Macau através do modelo de \"coinvestimento governo + privado\"."},
     "url": "https://www.gov.mo/zh-hant/news/1191808/"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "澳門科技研發產業園", "zh-CN": "澳门科技研发产业园",
               "en": "Macao Science and Technology Research and Development Industrial Park",
               "pt": "Parque Industrial de Investigação e Desenvolvimento Tecnológico de Macau"},
     "summary": {"zh-TW": "聚焦生物醫藥、集成電路、數字科技、航天科技四大領域的科創園區，定位為內地優質科企出海陣地與海外前沿科技項目落戶服務站。",
                 "zh-CN": "聚焦生物医药、集成电路、数字科技、航天科技四大领域的科创园区，定位为内地优质科企出海阵地与海外前沿科技项目落户服务站。",
                 "en": "An innovation park focused on biomedicine, integrated circuits, digital technology and aerospace technology, serving as a launchpad for mainland tech firms going global and a landing base for overseas frontier projects.",
                 "pt": "Parque de inovação focado em biomedicina, circuitos integrados, tecnologia digital e aeroespacial, servindo de base para empresas tecnológicas do continente se internacionalizarem e para projetos estrangeiros se instalarem."},
     "url": "https://www.dsedt.gov.mo/zh_MO/web/public/pg_stipc"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "支持澳門首店經濟發展計劃", "zh-CN": "支持澳门首店经济发展计划",
               "en": "Programme for Supporting the Development of Macao First-Store Economy",
               "pt": "Programa de Apoio ao Desenvolvimento da Economia de Primeiras Lojas de Macau"},
     "summary": {"zh-TW": "向國際品牌及內地、港澳台品牌在澳門開設首間實體店提供啟動及經營開支資助，進駐指定社區設疊加資助。",
                 "zh-CN": "向国际品牌及内地、港澳台品牌在澳门开设首间实体店提供启动及经营开支资助，进驻指定社区设叠加资助。",
                 "en": "Subsidies for international brands and brands from the mainland, Hong Kong, Macao and Taiwan opening their first physical store in Macao, with additional support for designated communities.",
                 "pt": "Subsídios para marcas internacionais e do continente, Hong Kong, Macau e Taiwan abrirem a sua primeira loja física em Macau, com apoio adicional em comunidades designadas."},
     "url": "https://www.ipim.gov.mo/zh-hant/investment-promotion/programme-for-supporting-the-development-of-macao-first-store-economy"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "會議及展覽激勵計劃", "zh-CN": "会议及展览激励计划",
               "en": "MICE Incentive Measures", "pt": "Medidas de Incentivo a Convenções e Exposições"},
     "summary": {"zh-TW": "資助在澳門舉辦的會展活動，涵蓋澳門與橫琴「一會展兩地」模式，每項活動資助上限300萬澳門元。",
                 "zh-CN": "资助在澳门举办的会展活动，涵盖澳门与横琴「一会展两地」模式，每项活动资助上限300万澳门元。",
                 "en": "Funding for MICE events held in Macao, covering the \"one event, two venues\" model between Macao and Hengqin, up to MOP 3 million per event.",
                 "pt": "Financiamento de eventos MICE realizados em Macau, incluindo o modelo \"um evento, dois locais\" entre Macau e Hengqin, até 3 milhões de patacas por evento."},
     "url": "https://www.ipim.gov.mo/zh-hant/mice/the-incentive-measures/"},
    {"region": "macao", "year": "2026",
     "title": {"zh-TW": "澳門國際科技產業中心", "zh-CN": "澳门国际科技产业中心",
               "en": "Macao International Technology Industry Center",
               "pt": "Centro Internacional da Indústria Tecnológica de Macau"},
     "summary": {"zh-TW": "由經科局、科技基金、招商投資促進局共建的科企落戶載體，首批科技企業已進駐，同場啟動「澳門招商大使」計劃。",
                 "zh-CN": "由经科局、科技基金、招商投资促进局共建的科企落户载体，首批科技企业已进驻，同场启动「澳门招商大使」计划。",
                 "en": "A landing platform for tech enterprises jointly built by DSEDT, FDCT and IPIM, with the first batch of tech companies settled in, alongside the launch of the \"Macao Investment Promotion Ambassador\" programme.",
                 "pt": "Plataforma de instalação de empresas tecnológicas construída conjuntamente pela DSEDT, FDCT e IPIM, com a primeira leva de empresas já instalada, e lançamento do programa \"Embaixador de Promoção de Investimento de Macau\"."},
     "url": "https://www.gsef.gov.mo/zh/posts/11928"},
    {"region": "macao", "year": {"zh-TW": "長期", "zh-CN": "长期", "en": "Ongoing", "pt": "Contínuo"},
     "title": {"zh-TW": "投資者一站式服務", "zh-CN": "投资者一站式服务",
               "en": "One-Stop Service for Investors", "pt": "Serviço de Balcão Único para Investidores"},
     "summary": {"zh-TW": "招商投資促進局提供專人跟進落戶、協調成立公司手續等一站式服務。",
                 "zh-CN": "招商投资促进局提供专人跟进落户、协调成立公司手续等一站式服务。",
                 "en": "IPIM provides one-stop services including dedicated follow-up for investors and coordination of company incorporation procedures.",
                 "pt": "O IPIM oferece serviços de balcão único, incluindo acompanhamento personalizado e coordenação dos procedimentos de constituição de empresas."},
     "url": "https://www.gov.mo/zh-hant/services/ps-1417/"},
    {"region": "hengqin", "year": "2022起",
     "title": {"zh-TW": "企業所得稅15%優惠", "zh-CN": "企业所得税15%优惠",
               "en": "15% Corporate Income Tax Incentive", "pt": "Incentivo de Imposto sobre Rendimento Empresarial de 15%"},
     "summary": {"zh-TW": "設在橫琴深合區、以優惠目錄產業為主營業務並實質性運營的企業，減按15%徵收企業所得稅。",
                 "zh-CN": "设在横琴深合区、以优惠目录产业为主营业务并实质性运营的企业，减按15%征收企业所得税。",
                 "en": "Enterprises established in the Hengqin Cooperation Zone with substantive operations in encouraged industries enjoy a reduced 15% corporate income tax rate.",
                 "pt": "Empresas estabelecidas na Zona de Cooperação de Hengqin, com operações substantivas em indústrias incentivadas, beneficiam de uma taxa reduzida de 15% de imposto sobre o rendimento."},
     "url": "https://www.hengqin.gov.cn/lab/zccx/gjzc/content/post_3510124.html"},
    {"region": "hengqin", "year": "2026–2027",
     "title": {"zh-TW": "個人所得稅優惠延續（澳人澳稅）", "zh-CN": "个人所得税优惠延续（澳人澳税）",
               "en": "Extension of Individual Income Tax Incentives (Macao Tax for Macao Residents)",
               "pt": "Extensão dos Incentivos de Imposto sobre Rendimento Individual (Regime Fiscal de Macau para Residentes)"},
     "summary": {"zh-TW": "在合作區工作的境內外高端緊缺人才個稅超過15%部分免徵；澳門居民個稅超過澳門稅負部分免徵。財稅〔2026〕2號。",
                 "zh-CN": "在合作区工作的境内外高端紧缺人才个税超过15%部分免征；澳门居民个税超过澳门税负部分免征。财税〔2026〕2号。",
                 "en": "High-end and urgently needed talents working in the zone are exempt from individual income tax above 15%; Macao residents are exempt from tax exceeding the Macao tax burden. Caishui [2026] No. 2.",
                 "pt": "Talentos de alto nível e escassos que trabalhem na zona ficam isentos do imposto individual acima de 15%; residentes de Macau ficam isentos da parcela que exceda a carga fiscal de Macau. Caishui [2026] n.º 2."},
     "url": "https://www.hengqin.gov.cn/invest-hengqin/hqzx/news/zcdt/content/post_3878127.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "橫琴深合區產業發展規劃（2025–2029年）", "zh-CN": "横琴深合区产业发展规划（2025–2029年）",
               "en": "Hengqin Cooperation Zone Industrial Development Plan (2025–2029)",
               "pt": "Plano de Desenvolvimento Industrial da Zona de Cooperação de Hengqin (2025–2029)"},
     "summary": {"zh-TW": "構建科技研發和高端製造、中醫藥等澳門品牌工業、文旅會展商貿、現代金融四大產業片區，2029年「四新」產業增加值佔GDP約65%。",
                 "zh-CN": "构建科技研发和高端制造、中医药等澳门品牌工业、文旅会展商贸、现代金融四大产业片区，2029年「四新」产业增加值占GDP约65%。",
                 "en": "Builds four industrial clusters: tech R&D and high-end manufacturing, Macao-branded industries such as traditional Chinese medicine, cultural tourism, MICE and commerce, and modern finance; \"four new\" industries to account for about 65% of GDP by 2029.",
                 "pt": "Constrói quatro clusters industriais: I&D tecnológica e manufactura avançada, indústrias de marca de Macau como a medicina tradicional chinesa, turismo cultural, convenções e comércio, e finanças modernas; as \"quatro novas\" indústrias representarão cerca de 65% do PIB em 2029."},
     "url": "https://www.gdhmo.gov.cn/ygazdhzpt/content/post_97158.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "生物醫藥大健康產業扶持實施細則", "zh-CN": "生物医药大健康产业扶持实施细则",
               "en": "Implementation Rules for Supporting the Biomedicine and Big Health Industry",
               "pt": "Regras de Implementação de Apoio à Indústria Biomédica e de Grande Saúde"},
     "summary": {"zh-TW": "對標桿項目落戶、研發、臨床、註冊等環節給予專項資金支持，直接對接澳門「1+4」產業策略。",
                 "zh-CN": "对标杆项目落户、研发、临床、注册等环节给予专项资金支持，直接对接澳门「1+4」产业策略。",
                 "en": "Special funding for landmark projects covering settlement, R&D, clinical trials and registration, directly aligned with Macao's \"1+4\" industrial strategy.",
                 "pt": "Financiamento especial para projetos emblemáticos nas fases de instalação, I&D, ensaios clínicos e registo, alinhado com a estratégia industrial \"1+4\" de Macau."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/zcfg/gfxwj/content/post_3801996.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "金融產業高質量發展扶持辦法", "zh-CN": "金融产业高质量发展扶持办法",
               "en": "Measures for Supporting High-Quality Development of the Financial Industry",
               "pt": "Medidas de Apoio ao Desenvolvimento de Alta Qualidade da Indústria Financeira"},
     "summary": {"zh-TW": "對落戶合作區的金融機構、金融科技企業給予落戶獎勵、租金補貼、業務發展扶持，配合澳門現代金融產業發展。",
                 "zh-CN": "对落户合作区的金融机构、金融科技企业给予落户奖励、租金补贴、业务发展扶持，配合澳门现代金融产业发展。",
                 "en": "Settlement rewards, rent subsidies and business development support for financial institutions and fintech enterprises in the zone, complementing Macao's modern finance industry.",
                 "pt": "Prémios de instalação, subsídios de renda e apoio ao desenvolvimento de negócios para instituições financeiras e empresas fintech na zona, complementando a indústria financeira moderna de Macau."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/zcfg/gfxwj/content/post_3863296.html"},
    {"region": "hengqin", "year": "2024起",
     "title": {"zh-TW": "澳門青年創新創業扶持", "zh-CN": "澳门青年创新创业扶持",
               "en": "Support for Macao Youth Innovation and Entrepreneurship",
               "pt": "Apoio à Inovação e ao Empreendedorismo dos Jovens de Macau"},
     "summary": {"zh-TW": "經認定的澳門青年創業企業可享辦公場地租金扶持與創業獎勵，澳青創新創業基地享活動扶持。",
                 "zh-CN": "经认定的澳门青年创业企业可享办公场地租金扶持与创业奖励，澳青创新创业基地享活动扶持。",
                 "en": "Recognised Macao youth startups can receive office rent support and entrepreneurship rewards, with activity support for Macao youth innovation and entrepreneurship bases.",
                 "pt": "Startups de jovens de Macau reconhecidas podem beneficiar de apoio à renda de escritórios e prémios de empreendedorismo, com apoio a actividades nas bases de inovação e empreendedorismo juvenil."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/tzgg/gg/content/post_3834693.html"},
]


# 社評專欄：會長楊誠《澳門日報》社論（2026-09-30）
# column=True → 洞察列表頁頂部單獨「社評專欄」section；author/source → 詳情頁署名與原文出處
oped_article = {
    "date": "2026-09-30", "slug": "macao-strategic-pivot-shock-absorber", "column": True,
    "category": {"zh-TW": "社評專欄", "zh-CN": "社评专栏", "en": "Op-Ed", "pt": "Coluna de Opinião"},
    "title": {"zh-TW": "澳門立戰略支點　當開放大局的減震墊", "zh-CN": "澳门立战略支点　当开放大局的减震垫",
              "en": "Macao as a Strategic Pivot: A Shock Absorber for the Nation's Opening-Up",
              "pt": "Macau como Pivô Estratégico: Amortecedor da Abertura Nacional"},
    "excerpt": {"zh-TW": "澳門應在國家開放大局中擔當戰略支點，當好企業出海的“減震墊”，讓出海從驚險一躍變為一次有準備的軟着陸。",
                "zh-CN": "澳门应在国家开放大局中担当战略支点，当好企业出海的“减震垫”，让出海从惊险一跃变为一次有准备的软着陆。",
                "en": "Macao should serve as a strategic pivot in the nation's opening-up and a \"shock absorber\" for enterprises going global, turning a daring leap into a well-prepared soft landing.",
                "pt": "Macau deve assumir-se como pivô estratégico na abertura nacional e \"amortecedor\" das empresas que se internacionalizam, transformando um salto arriscado numa aterragem suave e preparada."},
    "author": {"name": {"zh-TW": "楊誠", "zh-CN": "杨诚", "en": "Yang Cheng", "pt": "Yang Cheng"},
               "title": {"zh-TW": "澳門財經科技與教育發展學會會長、澳門數字創新協會理事長",
                         "zh-CN": "澳门财经科技与教育发展学会会长、澳门数字创新协会理事长",
                         "en": "President of MFTEDA and Chairman of the Macao Digital Innovation Association",
                         "pt": "Presidente da MFTEDA e Presidente da Associação de Inovação Digital de Macau"}},
    "source": {"name": {"zh-TW": "澳門日報", "zh-CN": "澳门日报", "en": "Macao Daily News", "pt": "Jornal Ou Mun"},
               "url": "https://www.macaodaily.com/html/2026-09/30/content_1937056.htm"},
    "images": [
        {"file": "unesco-1.webp", "after": 1,
         "caption": {"zh-TW": "楊誠會長於法國巴黎聯合國教科文組織總部", "zh-CN": "杨诚会长于法国巴黎联合国教科文组织总部",
                     "en": "President Yang Cheng at UNESCO Headquarters, Paris", "pt": "Presidente Yang Cheng na Sede da UNESCO, Paris"}},
        {"file": "unesco-2.webp", "after": 6,
         "caption": {"zh-TW": "楊誠會長於聯合國教科文組織總部留影", "zh-CN": "杨诚会长于联合国教科文组织总部留影",
                     "en": "President Yang Cheng at UNESCO Headquarters", "pt": "Presidente Yang Cheng na Sede da UNESCO"}},
    ],
    "body": {
        "zh-TW": [
            "深夜，智能燈具企業負責人羅先生還在和團隊一起，跨時區與巴西客戶逐條敲定合同細節。產品拿到了意向訂單，可葡語合同怎麼簽、貨款怎麼結、標準怎麼認證、糾紛去哪裡仲裁──四道關卡，道道上寫着“不確定”三個字。這不是一家企業的遭遇，而是千千萬萬中國企業出海的共同寫照。",
            "八月十八日，《澳門特別行政區經濟和社會發展第三個五年規劃（二○二六至二○三○年）》正式公佈。這份主動對接國家“十五五”規劃、全文十篇三十六章的綱領性文件，回答的正是那位企業主的深夜之問，也是一道時代之問：小城市如何在國家大戰略中找到大位置？筆者認為，答案不在體量，而在定位──澳門當立的位置，是國家開放大局中的戰略支點；而支點發揮作用的方式，是當好企業出海的“減震墊”，讓出海不再是驚險一躍，而是一次有準備的軟着陸。",
            "關於澳門，坊間曾流行兩種看法：一種說，澳門不過是一座休閒旅遊城市，談何服務國家開放大局；另一種說，澳門要做平台，就得複製香港、新加坡的路。但只要看幾個事實，便知兩種說法都只說對了一半。國家賦予澳門“世界旅遊休閒中心”、“中國與葡語國家商貿合作服務平台”的定位，本身就內含着服務國家開放大局的使命；澳門作為自由港和單獨關稅區，四百多年中西交往史，沉澱下與葡語國家之間難以替代的制度接口。更難得的是社會共識──規劃編制歷時四十天公開諮詢，共收到一千七百一十六份、合共八千二百三十條意見，正面評價佔九成二。一條路徑能凝聚這樣的民意基礎，本身就說明它不是辦公室裡想出來的，而是從澳門的土壤裡長出來的。",
            "這塊“減震墊”的價值，在於把“一躍”變成“落地”，其功能體現在三個層面。一是把不確定性消化在專業服務裡：以法律、會計、金融、仲裁等配套，讓企業不必在陌生的規則環境中獨行；二是把風險處置留在體系之內：對已出海而遭遇硬着陸的企業，一企一策、專家陪跑，助其轉危為機──“減震墊”的作用，既在緩衝，也在回彈；三是把數字時代的合規門檻轉化為服務能力：善用科技手段與人工智能工具，協助企業構建合法合規的海外數字資產，減少數字領域的制度顛簸。中國企業出海，尤其是中小微企業，缺的從來不是勇氣，而是緩衝。",
            "更值得注意的是路徑的差異化。澳門主攻中小微企業與輕資產領域，以精準對接的平台、專項支持計劃和“以大帶小”的協作生態，把出海門檻降到最低，讓普惠紅利覆蓋最廣大的企業群體；同時，依託橫琴粵澳深度合作區的疊加優勢，穩妥探索境外合規數字資產業務，在科技研發產業園落成之前，先立起科技與金融雙輪驅動的架勢。這不是與香港、新加坡爭奪甚麼版圖，而是為國家開放版圖補上一塊空缺的拼圖──發揮澳門所長，服務國家所需。當然，一個支點要真正撬動國家開放的大局，必須把制度優勢轉譯為企業可感的服務，必須把差異化的定位守成難以替代的位置──兩個“必須”之間，正是“三五”規劃從藍圖走向現實的全部工作量。",
            "藍圖已繪就，關鍵在落實。“減震墊”不會自己長出來，沿着“事前、事中、事後”三個環節，政府、業界、學界各有功課。",
            "事前做緩衝，把不確定性消化在出發之前。建議政府盡快設立企業出海服務專班和一站式窗口，把葡語法律、會計、認證、仲裁整合為標準化的“出海服務包”，讓中小微企業尚未啟航，先看清航道上的暗礁──這是把澳門的制度稟賦，轉譯為國家高水平對外開放的可感服務。",
            "事中做承接，把個體經驗沉澱為公共資產。建議業界共建認證供應商庫與案例知識庫，以“以大帶小”的生態，讓先行者的經驗成為後來者的路基──一家企業踩過的坑，不該讓第二家再踩；這是把單個企業的試錯成本，轉化為國家開放體系的整體韌性。",
            "事後做回彈，把危機處置錘煉成一門學問。對已遭遇硬着陸的企業，一企一策、專家陪跑；學界則應把這些案例當真學問來做，多寫幾份管用的報告，多教幾位能用的學生，多陪幾家企業走過最難的那段路──統籌發展和安全，既要體現在國家的頂層設計裡，也要落到澳門這塊“減震墊”的每一根彈簧上。",
            "支點不是喊出來的，是一顆顆螺絲擰出來的；而擰螺絲的手，就在我們這一代澳門青年中間。",
            "行政主導體制給了澳門集中力量辦大事的效率，“一國兩制”給了澳門聯通中西的稟賦。習近平主席寄語澳門“登高望遠、海納百川、銳意進取”，這份囑託落到“三五”規劃，就是把澳門的發展命運與國家的開放大局緊緊聯在一起，讓“一國兩制”的制度優勢在服務國家所需中行穩致遠。這正是新時代“愛國愛澳”核心價值最具體的實踐。規劃的份量，不在十篇三十六章的字裡行間，而在千家萬戶企業的賬本上。歷史給予澳門的機遇，最終要落到那位深夜辦公室裡的企業主，能否睡個好覺上。",
            "澳門不必成為下一個香港或新加坡。但願五年之後，每一位深夜還在跨時區談生意的企業主，腳下都有一塊澳門造的“減震墊”──這，就是澳門對“國內國際循環相互促進”最樸素也最堅實的回答。",
        ],
        "zh-CN": [
            "深夜，智能灯具企业负责人罗先生还在和团队一起，跨时区与巴西客户逐条敲定合同细节。产品拿到了意向订单，可葡语合同怎么签、货款怎么结、标准怎么认证、纠纷去哪里仲裁──四道关卡，道道上写着“不确定”三个字。这不是一家企业的遭遇，而是千千万万中国企业出海的共同写照。",
            "八月十八日，《澳门特别行政区经济和社会发展第三个五年规划（二○二六至二○三○年）》正式公布。这份主动对接国家“十五五”规划、全文十篇三十六章的纲领性文件，回答的正是那位企业主的深夜之问，也是一道时代之问：小城市如何在国家大战略中找到大位置？笔者认为，答案不在体量，而在定位──澳门当立的位置，是国家开放大局中的战略支点；而支点发挥作用的方式，是当好企业出海的“减震垫”，让出海不再是惊险一跃，而是一次有准备的软着陆。",
            "关于澳门，坊间曾流行两种看法：一种说，澳门不过是一座休闲旅游城市，谈何服务国家开放大局；另一种说，澳门要做平台，就得复制香港、新加坡的路。但只要看几个事实，便知两种说法都只说对了一半。国家赋予澳门“世界旅游休闲中心”、“中国与葡语国家商贸合作服务平台”的定位，本身就内含着服务国家开放大局的使命；澳门作为自由港和单独关税区，四百多年中西交往史，沉淀下与葡语国家之间难以替代的制度接口。更难得的是社会共识──规划编制历时四十天公开咨询，共收到一千七百一十六份、合共八千二百三十条意见，正面评价占九成二。一条路径能凝聚这样的民意基础，本身就说明它不是办公室里想出来的，而是从澳门的土壤里长出来的。",
            "这块“减震垫”的价值，在于把“一跃”变成“落地”，其功能体现在三个层面。一是把不确定性消化在专业服务里：以法律、会计、金融、仲裁等配套，让企业不必在陌生的规则环境中独行；二是把风险处置留在体系之内：对已出海而遭遇硬着陆的企业，一企一策、专家陪跑，助其转危为机──“减震垫”的作用，既在缓冲，也在回弹；三是把数字时代的合规门槛转化为服务能力：善用科技手段与人工智能工具，协助企业构建合法合规的海外数字资产，减少数字领域的制度颠簸。中国企业出海，尤其是中小微企业，缺的从来不是勇气，而是缓冲。",
            "更值得注意的是路径的差异化。澳门主攻中小微企业与轻资产领域，以精准对接的平台、专项支持计划和“以大带小”的协作生态，把出海门槛降到最低，让普惠红利覆盖最广大的企业群体；同时，依托横琴粤澳深度合作区的叠加优势，稳妥探索境外合规数字资产业务，在科技研发产业园落成之前，先立起科技与金融双轮驱动的架势。这不是与香港、新加坡争夺甚么版图，而是为国家开放版图补上一块空缺的拼图──发挥澳门所长，服务国家所需。当然，一个支点要真正撬动国家开放的大局，必须把制度优势转译为企业可感的服务，必须把差异化的定位守成难以替代的位置──两个“必须”之间，正是“三五”规划从蓝图走向现实的全部工作量。",
            "蓝图已绘就，关键在落实。“减震垫”不会自己长出来，沿着“事前、事中、事后”三个环节，政府、业界、学界各有功课。",
            "事前做缓冲，把不确定性消化在出发之前。建议政府尽快设立企业出海服务专班和一站式窗口，把葡语法律、会计、认证、仲裁整合为标准化的“出海服务包”，让中小微企业尚未启航，先看清航道上的暗礁──这是把澳门的制度禀赋，转译为国家高水平对外开放的可感服务。",
            "事中做承接，把个体经验沉淀为公共资产。建议业界共建认证供应商库与案例知识库，以“以大带小”的生态，让先行者的经验成为后来者的路基──一家企业踩过的坑，不该让第二家再踩；这是把单个企业的试错成本，转化为国家开放体系的整体韧性。",
            "事后做回弹，把危机处置锤炼成一门学问。对已遭遇硬着陆的企业，一企一策、专家陪跑；学界则应把这些案例当真学问来做，多写几份管用的报告，多教几位能用的学生，多陪几家企业走过最难的那段路──统筹发展和安全，既要体现在国家的顶层设计里，也要落到澳门这块“减震垫”的每一根弹簧上。",
            "支点不是喊出来的，是一颗颗螺丝拧出来的；而拧螺丝的手，就在我们这一代澳门青年中间。",
            "行政主导体制给了澳门集中力量办大事的效率，“一国两制”给了澳门联通中西的禀赋。习近平主席寄语澳门“登高望远、海纳百川、锐意进取”，这份嘱托落到“三五”规划，就是把澳门的发展命运与国家的开放大局紧紧联在一起，让“一国两制”的制度优势在服务国家所需中行稳致远。这正是新时代“爱国爱澳”核心价值最具体的实践。规划的份量，不在十篇三十六章的字里行间，而在千家万户企业的账本上。历史给予澳门的机遇，最终要落到那位深夜办公室里的企业主，能否睡个好觉上。",
            "澳门不必成为下一个香港或新加坡。但愿五年之后，每一位深夜还在跨时区谈生意的企业主，脚下都有一块澳门造的“减震垫”──这，就是澳门对“国内国际循环相互促进”最朴素也最坚实的回答。",
        ],
        "en": [
            "Late at night, Mr. Lo, head of a smart-lighting company, was still working with his team across time zones, finalizing contract details line by line with a Brazilian client. The product had won a letter of intent—but how to sign a Portuguese-language contract, how to settle payment, how to certify standards, where to arbitrate disputes: four hurdles, each marked with the word \"uncertainty.\" This is not the story of one company; it is the shared portrait of countless Chinese enterprises going global.",
            "On August 18, the Third Five-Year Plan for Economic and Social Development of the Macao Special Administrative Region (2026–2030) was officially released. This programmatic document—ten parts and thirty-six chapters, proactively aligned with the nation's 15th Five-Year Plan—answers precisely that business owner's late-night question, and a question of our times: how can a small city find a big place in a national strategy? In my view, the answer lies not in size but in positioning. The position Macao should occupy is that of a strategic pivot in the nation's opening-up; and the way this pivot works is by serving as a \"shock absorber\" for enterprises going global—turning a daring leap into a well-prepared soft landing.",
            "Two views about Macao once circulated. One held that Macao is merely a leisure and tourism city, hardly fit to serve the nation's opening-up; the other held that to be a platform, Macao must copy the paths of Hong Kong or Singapore. A few facts show both are only half right. The nation's designation of Macao as a \"World Centre of Tourism and Leisure\" and a \"Commercial and Trade Cooperation Service Platform between China and Portuguese-speaking Countries\" inherently carries the mission of serving the nation's opening-up. As a free port and separate customs territory with over four centuries of East–West exchange, Macao has built an institutional interface with the Portuguese-speaking countries that is hard to replace. Rarer still is the social consensus: during forty days of public consultation on the plan, 1,716 submissions totalling 8,230 comments were received, 92 percent of them positive. A path that commands such popular support was not devised in an office—it grew out of Macao's own soil.",
            "The value of this \"shock absorber\" lies in turning a \"leap\" into a \"landing,\" and it functions on three levels. First, it digests uncertainty through professional services: legal, accounting, financial and arbitration support, so that enterprises need not navigate an unfamiliar rules environment alone. Second, it keeps risk resolution within the system: for companies that have gone global and suffered a hard landing, tailored \"one enterprise, one policy\" support and expert accompaniment help them turn crisis into opportunity—the absorber cushions, but it also rebounds. Third, it converts the compliance thresholds of the digital era into service capability: making good use of technology and artificial-intelligence tools to help enterprises build lawful, compliant overseas digital assets, reducing institutional turbulence in the digital realm. What Chinese enterprises going global—especially micro, small and medium-sized ones—have never lacked is courage; what they lack is cushioning.",
            "Equally notable is the differentiated path. Macao focuses on MSMEs and asset-light sectors, lowering entry barriers to a minimum through precisely matched platforms, dedicated support programmes and a \"big leading small\" ecosystem of collaboration, so that inclusive benefits reach the broadest business community. At the same time, drawing on the combined advantages of the Guangdong-Macao In-Depth Cooperation Zone in Hengqin, Macao prudently explores compliant offshore digital-asset businesses—putting in place the twin engines of technology and finance even before the science and technology R&D industrial park is completed. This is not a contest with Hong Kong or Singapore for territory, but the missing piece in the nation's map of opening-up: bringing what Macao does best to serve what the nation needs. Of course, for a pivot to truly move the whole of the nation's opening-up, institutional advantages must be translated into services enterprises can feel, and a differentiated position must be consolidated into an irreplaceable one—between these two \"musts\" lies the entire workload of turning the Third Five-Year Plan from blueprint into reality.",
            "The blueprint is drawn; delivery is the key. A \"shock absorber\" does not grow by itself. Across the three stages—before, during and after—government, industry and academia each have homework to do.",
            "Before departure: cushion, digesting uncertainty in advance. The government should promptly set up a dedicated task force and a one-stop window for enterprises going global, integrating Portuguese-language legal, accounting, certification and arbitration services into a standardized \"going-global service package,\" so that MSMEs can see the reefs along the route before they set sail. This translates Macao's institutional endowment into tangible services for the nation's high-standard opening-up.",
            "During the journey: carry through, turning individual experience into public assets. Industry should jointly build a pool of certified service providers and a case knowledge base, so that under a \"big leading small\" ecosystem the experience of pioneers becomes the roadbed for followers—a pit one company has fallen into should not trap a second. This converts the trial-and-error costs of individual firms into the overall resilience of the nation's opening-up system.",
            "After the event: rebound, honing crisis management into a discipline. For companies that have suffered a hard landing, apply \"one enterprise, one policy\" with expert accompaniment; academia should treat these cases as serious scholarship—writing more useful reports, training more capable students, and walking more companies through the hardest stretch of the road. Coordinating development and security must be reflected not only in the nation's top-level design, but also in every single spring of Macao's \"shock absorber.\"",
            "A pivot is not proclaimed; it is fastened screw by screw. And the hands tightening those screws are among this generation of Macao's young people.",
            "The executive-led system gives Macao the efficiency to concentrate resources on major undertakings; \"One Country, Two Systems\" gives Macao the endowment to connect China and the West. President Xi Jinping urged Macao to \"stand tall and look far, embrace all rivers, and forge ahead with resolve.\" Brought into the Third Five-Year Plan, this charge binds Macao's destiny tightly to the nation's opening-up, letting the institutional advantages of \"One Country, Two Systems\" go steady and far in serving the nation's needs. This is the most concrete practice of the core value of \"loving the country and loving Macao\" in the new era. The weight of the plan lies not in the lines of its ten parts and thirty-six chapters, but in the ledgers of thousands of enterprises. The opportunity history has given Macao must ultimately come down to whether that business owner in the late-night office can get a good night's sleep.",
            "Macao need not become the next Hong Kong or Singapore. May it be that, five years from now, every business owner negotiating across time zones late into the night has a Macao-made \"shock absorber\" beneath their feet. This is Macao's simplest and sturdiest answer to the \"mutual reinforcement of domestic and international circulation.\"",
        ],
        "pt": [
            "Já de madrugada, o senhor Lo, responsável por uma empresa de iluminação inteligente, continuava com a sua equipa, através de fusos horários, a ultimar ponto por ponto os detalhes do contrato com um cliente brasileiro. O produto tinha obtido uma encomenda de intenção, mas como assinar um contrato em português, como liquidar o pagamento, como certificar as normas, onde arbitrar os litígios — quatro barreiras, cada uma marcada pela palavra \"incerteza\". Não é a experiência de uma só empresa, mas o retrato comum de incontáveis empresas chinesas que se internacionalizam.",
            "A 18 de agosto, foi oficialmente publicado o Terceiro Plano Quinquenal de Desenvolvimento Económico e Social da Região Administrativa Especial de Macau (2026–2030). Este documento programático — dez partes e trinta e seis capítulos, que se articula proactivamente com o 15.º Plano Quinquenal nacional — responde precisamente à pergunta que inquietava aquele empresário de madrugada, e também a uma interrogação da época: como pode uma pequena cidade encontrar um grande lugar na estratégia nacional? Na minha opinião, a resposta não está na dimensão, mas no posicionamento: o lugar que Macau deve ocupar é o de pivô estratégico na abertura nacional; e a forma de este pivô actuar é servir de \"amortecedor\" para as empresas que se internacionalizam, fazendo com que a saída deixe de ser um salto arriscado e passe a ser uma aterragem suave e preparada.",
            "Sobre Macau circulavam duas opiniões. Uma dizia que Macau não passa de uma cidade de turismo e lazer, incapaz de servir a abertura nacional; outra dizia que, para ser plataforma, Macau tinha de copiar os caminhos de Hong Kong ou de Singapura. Basta olhar para alguns factos para ver que ambas acertam apenas metade. A posição atribuída pelo país a Macau de \"Centro Mundial de Turismo e Lazer\" e de \"Plataforma de Serviços para a Cooperação Comercial entre a China e os Países de Língua Portuguesa\" encerra em si a missão de servir a abertura nacional; enquanto porto franco e território aduaneiro separado, com mais de quatro séculos de contactos entre a China e o Ocidente, Macau sedimentou uma interface institucional com os países de língua portuguesa difícil de substituir. Mais raro ainda é o consenso social — a elaboração do plano incluiu quarenta dias de consulta pública, com 1.716 contributos e um total de 8.230 opiniões, 92% das quais favoráveis. Um caminho capaz de congregar tal base popular não foi imaginado num gabinete: cresceu do próprio solo de Macau.",
            "O valor deste \"amortecedor\" está em transformar o \"salto\" em \"aterragem\", e a sua função manifesta-se em três planos. Primeiro, digerir a incerteza através de serviços profissionais: com apoios jurídicos, contabilísticos, financeiros e de arbitragem, para que as empresas não caminhem sozinhas num ambiente de regras desconhecidas. Segundo, manter a gestão de riscos dentro do sistema: para as empresas já internacionalizadas que sofreram uma aterragem forçada, \"uma empresa, uma política\" e acompanhamento por especialistas, ajudando-as a transformar a crise em oportunidade — o \"amortecedor\" serve tanto para amortecer como para fazer ressaltar. Terceiro, converter os limiares de conformidade da era digital em capacidade de serviço: fazer bom uso da tecnologia e das ferramentas de inteligência artificial para ajudar as empresas a construir activos digitais no estrangeiro legais e conformes, reduzindo as turbulências institucionais no domínio digital. Às empresas chinesas que se internacionalizam — sobretudo às micro, pequenas e médias — nunca faltou coragem; falta-lhes amortecimento.",
            "Mais notável ainda é a diferenciação do percurso. Macau aposta nas micro, pequenas e médias empresas e nos sectores de activos leves, reduzindo ao mínimo as barreiras de entrada através de plataformas de articulação precisa, programas de apoio específicos e um ecossistema de colaboração em que \"os grandes levam os pequenos\", de modo a que os dividendos inclusivos cubram o mais amplo universo empresarial; ao mesmo tempo, apoiando-se nas vantagens sobrepostas da Zona de Cooperação Aprofundada Guangdong-Macau em Hengqin, explora com prudência negócios de activos digitais conformes no exterior, erguendo desde já — antes mesmo da conclusão do parque industrial de investigação e desenvolvimento tecnológico — a arquitectura de dupla propulsão da tecnologia e das finanças. Não se trata de disputar território com Hong Kong ou Singapura, mas de preencher uma peça que faltava no mapa da abertura nacional: pôr as forças de Macau ao serviço das necessidades do país. Naturalmente, para que um pivô alavanque de facto a abertura nacional, é preciso traduzir as vantagens institucionais em serviços que as empresas possam sentir, e consolidar um posicionamento diferenciado num lugar insubstituível — entre estes dois \"é preciso\" reside todo o trabalho necessário para levar o Terceiro Plano Quinquenal do projecto à realidade.",
            "O projecto está traçado; a chave está na execução. O \"amortecedor\" não nasce por si. Ao longo dos três momentos — antes, durante e depois — o Governo, o sector empresarial e o meio académico têm cada um os seus deveres.",
            "Antes, amortecer: digerir a incerteza antes da partida. Sugere-se que o Governo crie quanto antes um grupo de trabalho dedicado e um balcão único de serviços à internacionalização das empresas, integrando o direito, a contabilidade, a certificação e a arbitragem em língua portuguesa num \"pacote de serviços de internacionalização\" normalizado, para que as micro, pequenas e médias empresas, antes de levantar âncora, vejam com clareza os recifes da rota. É traduzir o património institucional de Macau em serviços tangíveis para a abertura de alto nível do país.",
            "Durante, dar suporte: sedimentar a experiência individual em património público. Sugere-se que o sector empresarial construa em conjunto um repositório de fornecedores certificados e uma base de conhecimento de casos, para que, num ecossistema em que \"os grandes levam os pequenos\", a experiência dos pioneiros sirva de alicerce aos que vêm depois — o buraco em que uma empresa caiu não deve apanhar uma segunda. É converter o custo de tentativa e erro de cada empresa na resiliência global do sistema de abertura nacional.",
            "Depois, fazer ressaltar: forjar a gestão de crises numa disciplina. Para as empresas que sofreram uma aterragem forçada, \"uma empresa, uma política\" e acompanhamento por especialistas; o meio académico deve tratar estes casos como verdadeira ciência — escrever mais relatórios úteis, formar mais estudantes capazes, acompanhar mais empresas no troço mais difícil do caminho. A coordenação do desenvolvimento e da segurança deve reflectir-se não só na concepção de topo do país, mas também em cada mola deste \"amortecedor\" de Macau.",
            "Um pivô não se proclama: aparafusa-se, parafuso a parafuso. E as mãos que apertam esses parafusos estão entre os jovens desta geração de Macau.",
            "O sistema de primazia do executivo deu a Macau a eficiência de concentrar forças para grandes empreendimentos; \"Um País, Dois Sistemas\" deu a Macau o dom de ligar a China e o Ocidente. O Presidente Xi Jinping exortou Macau a \"erguer-se alto e olhar longe, acolher todos os rios, avançar com determinação\". Esta exortação, trazida para o Terceiro Plano Quinquenal, significa ligar estreitamente o destino de Macau à abertura nacional, fazendo com que as vantagens institucionais de \"Um País, Dois Sistemas\" avancem com estabilidade ao serviço das necessidades do país. É a prática mais concreta do valor central de \"amar a pátria e amar Macau\" na nova era. O peso do plano não está nas entrelinhas das suas dez partes e trinta e seis capítulos, mas nos livros de contas de milhares de empresas. A oportunidade que a história deu a Macau há-de, no fim, medir-se pela possibilidade de aquele empresário, no seu escritório de madrugada, poder dormir descansado.",
            "Macau não precisa de se tornar o próximo Hong Kong ou Singapura. Oxalá daqui a cinco anos, cada empresário que a altas horas negoceia através de fusos horários tenha debaixo dos pés um \"amortecedor\" feito em Macau — eis a resposta mais simples e mais sólida de Macau à \"promoção mútua da circulação nacional e internacional\".",
        ],
    },
}

# 研究洞察 6 articles (titles/categories/excerpts per language, dates fixed)
insights = [oped_article,
    {"date": "2026-03-15", "category": {"zh-TW": "數字經濟", "zh-CN": "数字经济", "en": "Digital Economy", "pt": "Economia Digital"},
     "title": {"zh-TW": "澳門數字經濟發展趨勢", "zh-CN": "澳门数字经济发展趋势", "en": "Digital Economy Trends in Macao", "pt": "Tendências da Economia Digital em Macau"},
     "excerpt": {"zh-TW": "分析澳門特區數字化轉型的機遇與挑戰", "zh-CN": "分析澳门特区数字化转型的机遇与挑战", "en": "Analysis of digital transformation opportunities and challenges in Macao SAR", "pt": "Análise de oportunidades e desafios da transformação digital na RAE de Macau"}},
    {"date": "2026-03-10", "category": {"zh-TW": "區域合作", "zh-CN": "区域合作", "en": "Regional Cooperation", "pt": "Cooperação Regional"},
     "title": {"zh-TW": "大灣區融合發展策略", "zh-CN": "大湾区融合发展策略", "en": "Greater Bay Area Integration Strategies", "pt": "Estratégias de Integração da Grande Baía"},
     "excerpt": {"zh-TW": "提升澳門在大灣區角色的政策建議", "zh-CN": "提升澳门在大湾区角色的政策建议", "en": "Policy recommendations for enhancing Macao's role in the Greater Bay Area", "pt": "Recomendações políticas para fortalecer o papel de Macau na Grande Baía"}},
    {"date": "2026-03-05", "category": {"zh-TW": "可持續金融", "zh-CN": "可持续金融", "en": "Sustainable Finance", "pt": "Finanças Sustentáveis"},
     "title": {"zh-TW": "ESG投資機遇", "zh-CN": "ESG投资机遇", "en": "ESG Investment Opportunities", "pt": "Oportunidades de Investimento ESG"},
     "excerpt": {"zh-TW": "探索可持續投資趨勢與綠色金融倡議", "zh-CN": "探索可持续投资趋势与绿色金融倡议", "en": "Exploring sustainable investment trends and green finance initiatives", "pt": "Explorando tendências de investimento sustentável e iniciativas de finanças verdes"}},
    {"date": "2026-02-28", "category": {"zh-TW": "現代金融", "zh-CN": "现代金融", "en": "Modern Finance", "pt": "Finanças Modernas"},
     "title": {"zh-TW": "人民幣國際化進展", "zh-CN": "人民币国际化进展", "en": "RMB Internationalization Progress", "pt": "Progresso da Internacionalização do RMB"},
     "excerpt": {"zh-TW": "人民幣跨境使用與金融合作的最新進展", "zh-CN": "人民币跨境使用与金融合作的最新进展", "en": "Latest developments in cross-border RMB usage and financial cooperation", "pt": "Últimos desenvolvimentos no uso transfronteiriço do RMB e cooperação financeira"}},
    {"date": "2026-02-20", "category": {"zh-TW": "創新", "zh-CN": "创新", "en": "Innovation", "pt": "Inovação"},
     "title": {"zh-TW": "文化與科技創新", "zh-CN": "文化与科技创新", "en": "Culture and Technology Innovation", "pt": "Inovação em Cultura e Tecnologia"},
     "excerpt": {"zh-TW": "科技如何改變澳門文化產業", "zh-CN": "科技如何改变澳门文化产业", "en": "How technology is transforming Macao's cultural industries", "pt": "Como a tecnologia está transformando as indústrias culturais de Macau"}},
    {"date": "2026-02-15", "category": {"zh-TW": "政策研究", "zh-CN": "政策研究", "en": "Policy Research", "pt": "Pesquisa Política"},
     "title": {"zh-TW": "自由貿易港監管最佳實踐", "zh-CN": "自由贸易港监管最佳实践", "en": "Free Trade Port Regulation Best Practices", "pt": "Melhores Práticas de Regulação de Porto de Livre Comércio"},
     "excerpt": {"zh-TW": "海關監管框架的國際比較", "zh-CN": "海关监管框架的国际比较", "en": "International comparison of customs regulation frameworks", "pt": "Comparação internacional de estruturas de regulação aduaneira"}},
]

# 新聞動態：學會公開新聞（含詳情頁 news/{slug}.html；source 為原文出處媒體與鏈接）
news = [
    {"date": "2026-08-27", "slug": "yang-cheng-third-five-year-plan-interview",
     "category": {"zh-TW": "媒體專訪", "zh-CN": "媒体专访", "en": "Media Interview", "pt": "Entrevista à Comunicação Social"},
     "title": {"zh-TW": "會長楊誠解讀「三五」規劃：澳門當立戰略支點之位　當好開放大局「減震墊」",
               "zh-CN": "会长杨诚解读「三五」规划：澳门当立战略支点之位　当好开放大局「减震垫」",
               "en": "President Yang Cheng on the Third Five-Year Plan: Macao Should Stand as a Strategic Pivot and a \"Shock Absorber\" for the Nation's Opening-Up",
               "pt": "Presidente Yang Cheng Interpreta o Terceiro Plano Quinquenal: Macau Deve Ser Pivô Estratégico e «Amortecedor» da Abertura Nacional"},
     "excerpt": {"zh-TW": "會長楊誠接受《濠江日報》專訪，解讀「三五」規劃：澳門當立戰略支點之位，當好企業出海的「減震墊」。",
                 "zh-CN": "会长杨诚接受《濠江日报》专访，解读「三五」规划：澳门当立战略支点之位，当好企业出海的「减震垫」。",
                 "en": "In an interview with Hou Kong Daily, President Yang Cheng shared his reading of the Third Five-Year Plan: Macao should stand as a strategic pivot and a \"shock absorber\" for enterprises going global.",
                 "pt": "Em entrevista ao Jornal Hou Kong, o Presidente Yang Cheng interpretou o Terceiro Plano Quinquenal: Macau deve assumir-se como pivô estratégico e «amortecedor» da abertura nacional."},
     "source": {"name": {"zh-TW": "濠江日報", "zh-CN": "濠江日报", "en": "Hou Kong Daily", "pt": "Jornal Hou Kong"},
                "url": "https://www.houkongdailynews.com/instantNews/156431"},
     "body": {
        "zh-TW": [
            "《澳門特別行政區經濟和社會發展第三個五年規劃（2026至2030年）》公佈後，本會會長、澳門數字創新協會理事長楊誠接受《濠江日報》專訪，解讀規劃亮點。他指出，規劃回答了「小城市如何在國家大戰略中找到大位置」的時代之問。",
            "楊誠認為，澳門當立於國家開放大局的戰略支點之位，當好企業出海的「減震墊」，讓出海從驚險一躍變為有準備的軟着陸。他沿着事前緩衝、事中承接、事後回彈三個環節提出建議：政府層面設立企業出海服務專班和一站式窗口，把葡語法律、會計、認證、仲裁整合為標準化的「出海服務包」；業界共建認證供應商庫與案例知識庫，讓先行者的經驗成為後來者的路基；學界則把危機處置案例轉化為研究與教學資源。",
            "楊誠強調，澳門應主攻中小微企業與輕資產領域，以精準對接的平台與專項支持計劃把出海門檻降到最低，讓普惠紅利覆蓋最廣大的企業群體；同時依託橫琴粵澳深度合作區的疊加優勢，穩妥探索境外合規數字資產業務，為國家開放版圖補上空缺的拼圖。",
            "「發揮澳門所長，服務國家所需。」楊誠表示，本會將圍繞「三五」規劃的落實持續開展研究與建言，助力澳門在國家高水平對外開放中發揮獨特作用。",
        ],
        "zh-CN": [
            "《澳门特别行政区经济和社会发展第三个五年规划（2026至2030年）》公布后，本会会长、澳门数字创新协会理事长杨诚接受《濠江日报》专访，解读规划亮点。他指出，规划回答了「小城市如何在国家大战略中找到大位置」的时代之问。",
            "杨诚认为，澳门当立于国家开放大局的战略支点之位，当好企业出海的「减震垫」，让出海从惊险一跃变为有准备的软着陆。他沿着事前缓冲、事中承接、事后回弹三个环节提出建议：政府层面设立企业出海服务专班和一站式窗口，把葡语法律、会计、认证、仲裁整合为标准化的「出海服务包」；业界共建认证供应商库与案例知识库，让先行者的经验成为后来者的路基；学界则把危机处置案例转化为研究与教学资源。",
            "杨诚强调，澳门应主攻中小微企业与轻资产领域，以精准对接的平台与专项支持计划把出海门槛降到最低，让普惠红利覆盖最广大的企业群体；同时依托横琴粤澳深度合作区的叠加优势，稳妥探索境外合规数字资产业务，为国家开放版图补上空缺的拼图。",
            "「发挥澳门所长，服务国家所需。」杨诚表示，本会将围绕「三五」规划的落实持续开展研究与建言，助力澳门在国家高水平对外开放中发挥独特作用。",
        ],
        "en": [
            "Following the release of the Third Five-Year Plan for Economic and Social Development of the Macao Special Administrative Region (2026–2030), MFTEDA President Yang Cheng, who is also Chairman of the Macao Digital Innovation Association, gave an interview to Hou Kong Daily analysing the plan's highlights. He noted that the plan answers the question of our times: \"How can a small city find a big place in a national strategy?\"",
            "Yang Cheng believes Macao should stand as a strategic pivot in the nation's opening-up and serve as a \"shock absorber\" for enterprises going global, turning a daring leap into a well-prepared soft landing. Along the three stages of pre-departure cushioning, mid-journey support and post-event rebound, he recommended that the government set up a dedicated task force and a one-stop window for enterprises going global, integrating Portuguese-language legal, accounting, certification and arbitration services into a standardized \"going-global service package\"; that industry jointly build a pool of certified service providers and a case knowledge base, so that the experience of pioneers becomes the roadbed for followers; and that academia turn crisis-management cases into research and teaching resources.",
            "Yang Cheng stressed that Macao should focus on micro, small and medium-sized enterprises and asset-light sectors, lowering entry barriers to a minimum through precisely matched platforms and dedicated support programmes so that inclusive benefits reach the broadest business community; meanwhile, relying on the combined advantages of the Guangdong-Macao In-Depth Cooperation Zone in Hengqin, Macao should prudently explore compliant offshore digital-asset businesses, filling a missing piece in the nation's map of opening-up.",
            "\"Bring what Macao does best to serve what the nation needs,\" Yang Cheng said, adding that MFTEDA will continue to conduct research and offer recommendations on the implementation of the Third Five-Year Plan, helping Macao play its unique role in the nation's high-standard opening-up.",
        ],
        "pt": [
            "Após a publicação do Terceiro Plano Quinquenal de Desenvolvimento Económico e Social da Região Administrativa Especial de Macau (2026–2030), o Presidente da MFTEDA e Presidente da Associação de Inovação Digital de Macau, Yang Cheng, concedeu uma entrevista ao Jornal Hou Kong para interpretar os pontos altos do plano, referindo que este responde à interrogação da época: «como pode uma pequena cidade encontrar um grande lugar na estratégia nacional?»",
            "Na opinião de Yang Cheng, Macau deve assumir a posição de pivô estratégico na abertura nacional e servir de «amortecedor» para as empresas que se internacionalizam, transformando um salto arriscado numa aterragem suave e preparada. Ao longo dos três momentos — amortecimento prévio, suporte intermédio e ressalto posterior — recomendou que o Governo crie um grupo de trabalho dedicado e um balcão único de serviços à internacionalização das empresas, integrando o direito, a contabilidade, a certificação e a arbitragem em língua portuguesa num «pacote de serviços de internacionalização» normalizado; que o sector empresarial construa em conjunto um repositório de fornecedores certificados e uma base de conhecimento de casos, fazendo da experiência dos pioneiros o alicerce dos que vêm depois; e que o meio académico transforme os casos de gestão de crises em recursos de investigação e de ensino.",
            "Yang Cheng sublinhou que Macau deve apostar nas micro, pequenas e médias empresas e nos sectores de activos leves, reduzindo ao mínimo as barreiras de entrada através de plataformas de articulação precisa e programas de apoio específicos, de modo a que os dividendos inclusivos cubram o mais amplo universo empresarial; ao mesmo tempo, apoiando-se nas vantagens sobrepostas da Zona de Cooperação Aprofundada Guangdong-Macau em Hengqin, Macau deve explorar com prudência negócios de activos digitais conformes no exterior, preenchendo uma peça que faltava no mapa da abertura nacional.",
            "«Pôr as forças de Macau ao serviço das necessidades do país», afirmou Yang Cheng, acrescentando que a MFTEDA continuará a desenvolver investigação e a apresentar propostas em torno da execução do Terceiro Plano Quinquenal, ajudando Macau a desempenhar o seu papel ímpar na abertura de alto nível do país.",
        ],
     }},
    {"date": "2026-05-12", "slug": "usj-du-wencai-changchun-appointment",
     "category": {"zh-TW": "學術合作", "zh-CN": "学术合作", "en": "Academic Cooperation", "pt": "Cooperação Académica"},
     "title": {"zh-TW": "聖若瑟大學杜文才教授受聘長春電子科技學院　本會秘書長韓婧怡出席見證",
               "zh-CN": "圣若瑟大学杜文才教授受聘长春电子科技学院　本会秘书长韩婧怡出席见证",
               "en": "USJ Professor Du Wencai Appointed Specially-Appointed Professor at Changchun College of Electronic Technology; MFTEDA Secretary-General Han Jingyi Witnesses Ceremony",
               "pt": "Professor Du Wencai da Universidade São José Nomeado Professor da Faculdade de Tecnologia Electrónica de Changchun com a Presença da Secretária-Geral da MFTEDA"},
     "excerpt": {"zh-TW": "聖若瑟大學杜文才教授受聘長春電子科技學院特聘教授，雙方商談碩博推薦與科研合作，本會秘書長韓婧怡出席見證。",
                 "zh-CN": "圣若瑟大学杜文才教授受聘长春电子科技学院特聘教授，双方商谈硕博推荐与科研合作，本会秘书长韩婧怡出席见证。",
                 "en": "Professor Du Wencai of the University of Saint Joseph was appointed specially-appointed professor at Changchun College of Electronic Technology, with discussions on postgraduate recommendation and research cooperation.",
                 "pt": "O professor Du Wencai da Universidade São José foi nomeado professor especialmente convidado da Faculdade de Tecnologia Electrónica de Changchun, tendo sido discutidas a recomendação de estudantes para pós-graduações e a cooperação científica."},
     "source": {"name": {"zh-TW": "濠江日報", "zh-CN": "濠江日报", "en": "Hou Kong Daily", "pt": "Jornal Hou Kong"},
                "url": "https://www.houkongdailynews.com/instantNews/149984"},
     "body": {
        "zh-TW": [
            "聖若瑟大學數據工程與科學學院院長杜文才教授於2026年5月12日訪問長春電子科技學院，獲聘為該校特聘教授。本會秘書長韓婧怡（兼任澳門博士智庫吉林聯絡辦主任）出席活動並見證聘任儀式。",
            "訪問期間，雙方就推薦長春電子科技學院學生赴聖若瑟大學攻讀碩士及博士學位事宜進行商談，並就科研合作、師資交流與人才培養等領域達成初步合作意向。",
            "杜文才教授以《人工智能與無人機配送》為題，為該校教師開展專題培訓，分享人工智能技術在物流配送領域的前沿應用與研究進展，獲與會教師熱烈反響。",
            "雙方表示，將以此次聘任為契機，推動兩校在科研協同、師資互訪與學生交流等方面的務實合作，促進澳門與內地高等教育資源的互聯互通。",
        ],
        "zh-CN": [
            "圣若瑟大学数据工程与科学学院院长杜文才教授于2026年5月12日访问长春电子科技学院，获聘为该校特聘教授。本会秘书长韩婧怡（兼任澳门博士智库吉林联络办主任）出席活动并见证聘任仪式。",
            "访问期间，双方就推荐长春电子科技学院学生赴圣若瑟大学攻读硕士及博士学位事宜进行商谈，并就科研合作、师资交流与人才培养等领域达成初步合作意向。",
            "杜文才教授以《人工智能与无人机配送》为题，为该校教师开展专题培训，分享人工智能技术在物流配送领域的前沿应用与研究进展，获与会教师热烈反响。",
            "双方表示，将以此次聘任为契机，推动两校在科研协同、师资互访与学生交流等方面的务实合作，促进澳门与内地高等教育资源的互联互通。",
        ],
        "en": [
            "Professor Du Wencai, Dean of the Faculty of Data Engineering and Science of the University of Saint Joseph (USJ), visited the Changchun College of Electronic Technology on 12 May 2026 and was appointed a specially-appointed professor of the college. MFTEDA Secretary-General Han Jingyi, who is also Director of the Jilin Liaison Office of the Macao Doctoral Think Tank, attended the event and witnessed the appointment ceremony.",
            "During the visit, the two sides discussed arrangements for recommending students of the college to pursue master's and doctoral degrees at the University of Saint Joseph, and reached preliminary intentions for cooperation in research collaboration, faculty exchanges and talent cultivation.",
            "Professor Du Wencai delivered a special training session for the college's teachers titled \"Artificial Intelligence and Drone Delivery,\" sharing frontier applications and research progress of AI technology in logistics and distribution, which was warmly received by the participating faculty.",
            "Both sides stated that they would take this appointment as an opportunity to promote pragmatic cooperation between the two institutions in collaborative research, mutual faculty visits and student exchanges, fostering the interconnection of higher education resources between Macao and the mainland.",
        ],
        "pt": [
            "O professor Du Wencai, director da Faculdade de Engenharia e Ciências de Dados da Universidade São José, visitou a 12 de maio de 2026 a Faculdade de Tecnologia Electrónica de Changchun, tendo sido nomeado professor especialmente convidado dessa instituição. A Secretária-Geral da MFTEDA, Han Jingyi, também directora do Gabinete de Ligação de Jilin do Think Tank dos Doutorados de Macau, esteve presente e testemunhou a cerimónia de nomeação.",
            "Durante a visita, as duas partes discutiram a recomendação de estudantes da Faculdade para a frequência de mestrados e doutoramentos na Universidade São José, chegando a intenções preliminares de cooperação nos domínios da investigação científica, do intercâmbio de docentes e da formação de talentos.",
            "O professor Du Wencai proferiu uma formação temática intitulada «Inteligência Artificial e Distribuição por Drones» para os docentes da instituição, partilhando aplicações de vanguarda e os avanços da investigação da tecnologia de IA na logística e na distribuição, recebendo uma calorosa receptividade.",
            "As duas partes manifestaram a intenção de, aproveitando esta nomeação como oportunidade, promover a cooperação pragmática entre as duas instituições na investigação colaborativa, nas visitas recíprocas de docentes e no intercâmbio de estudantes, fomentando a interligação dos recursos do ensino superior entre Macau e o interior da China.",
        ],
     }},
    {"date": "2026-04-10", "slug": "youth-employment-digital-workshop",
     "category": {"zh-TW": "青年培育", "zh-CN": "青年培育", "en": "Youth Development", "pt": "Formação de Jovens"},
     "title": {"zh-TW": "「數智時代『職』得擁有」澳門青年就業指導培訓講座圓滿舉行",
               "zh-CN": "「数智时代『职』得拥有」澳门青年就业指导培训讲座圆满举行",
               "en": "\"A Career Worth Having in the Digital-Intelligence Era\" — Macao Youth Employment Guidance Workshop Successfully Held",
               "pt": "Realizada Palestra de Orientação Profissional para Jovens de Macau na Era da Inteligência Digital"},
     "excerpt": {"zh-TW": "本會主辦、澳門基金會贊助的青年就業指導培訓講座舉行，五位專家分享數智時代就業機遇與AI求職技巧，助力澳門青年規劃職涯。",
                 "zh-CN": "本会主办、澳门基金会赞助的青年就业指导培训讲座举行，五位专家分享数智时代就业机遇与AI求职技巧，助力澳门青年规划职涯。",
                 "en": "An MFTEDA-organised, Macao Foundation-sponsored employment guidance workshop helped Macao youth explore career opportunities and AI-powered job-hunting skills in the digital-intelligence era.",
                 "pt": "Palestra de orientação profissional organizada pela MFTEDA com o apoio da Fundação Macau ajudou os jovens a explorar oportunidades de emprego e técnicas de procura de emprego com IA na era da inteligência digital."},
     "source": {"name": {"zh-TW": "濠江日報", "zh-CN": "濠江日报", "en": "Hou Kong Daily", "pt": "Jornal Hou Kong"},
                "url": "https://www.houkongdailynews.com/instantNews/148011"},
     "body": {
        "zh-TW": [
            "由本會主辦、澳門基金會贊助的「數智時代『職』得擁有」澳門青年就業指導培訓講座，日前在粵港澳大灣區國際人才驛站（澳門）圓滿舉行。活動旨在增強澳門在校大學生的數字化意識與人工智能技能，引導學生將數字化技能與職業規劃相結合。",
            "講座邀請五位來自學術界、企業界及人力資源領域的專家擔任主講，圍繞數智時代的就業機遇、AI賦能求職與面試技巧、科技創新與創業實踐等主題作分享，內容兼具前瞻性與實用性，幫助學生了解行業最新趨勢。",
            "互動環節上，學生踴躍提問，就簡歷撰寫、面試準備、職業方向選擇等問題與嘉賓深入交流，現場氣氛熱烈。",
            "主辦方勉勵學生主動擁抱數智時代的機遇，及早規劃職業生涯，提升數字素養與綜合競爭力；並表示將繼續舉辦同類活動，助力澳門青年高質量就業與成長。",
        ],
        "zh-CN": [
            "由本会主办、澳门基金会赞助的「数智时代『职』得拥有」澳门青年就业指导培训讲座，日前在粤港澳大湾区国际人才驿站（澳门）圆满举行。活动旨在增强澳门在校大学生的数字化意识与人工智能技能，引导学生将数字化技能与职业规划相结合。",
            "讲座邀请五位来自学术界、企业界及人力资源领域的专家担任主讲，围绕数智时代的就业机遇、AI赋能求职与面试技巧、科技创新与创业实践等主题作分享，内容兼具前瞻性与实用性，帮助学生了解行业最新趋势。",
            "互动环节上，学生踊跃提问，就简历撰写、面试准备、职业方向选择等问题与嘉宾深入交流，现场气氛热烈。",
            "主办方勉励学生主动拥抱数智时代的机遇，及早规划职业生涯，提升数字素养与综合竞争力；并表示将继续举办同类活动，助力澳门青年高质量就业与成长。",
        ],
        "en": [
            "The Macao youth employment guidance workshop \"A Career Worth Having in the Digital-Intelligence Era,\" organised by MFTEDA and sponsored by the Macao Foundation, was successfully held at the Guangdong–Hong Kong–Macao Greater Bay Area International Talent Hub (Macao). The event aimed to strengthen digital awareness and AI skills among Macao's university students, guiding them to integrate digital skills with career planning.",
            "Five experts from academia, industry and human resources were invited as speakers, sharing insights on employment opportunities in the digital-intelligence era, AI-empowered job hunting and interview techniques, and technological innovation and entrepreneurial practice. The content, both forward-looking and practical, helped students keep abreast of the latest industry trends.",
            "During the interactive session, students raised questions enthusiastically, engaging in in-depth exchanges with the speakers on résumé writing, interview preparation and career direction, in a warm and lively atmosphere.",
            "The organisers encouraged students to embrace the opportunities of the digital-intelligence era, plan their careers early, and enhance their digital literacy and overall competitiveness, adding that similar events will continue to be held to support Macao's youth in achieving high-quality employment and personal growth.",
        ],
        "pt": [
            "A palestra de orientação profissional para jovens de Macau «Uma Carreira que Vale a Pena na Era da Inteligência Digital», organizada pela MFTEDA e financiada pela Fundação Macau, realizou-se com êxito no Posto Internacional de Talentos da Grande Baía Guangdong-Hong Kong-Macau (Macau). A iniciativa visou reforçar a consciência digital e as competências em inteligência artificial dos estudantes universitários de Macau, orientando-os na articulação entre competências digitais e planeamento de carreira.",
            "Foram convidados cinco especialistas do meio académico, do sector empresarial e da área de recursos humanos, que partilharam conhecimentos sobre as oportunidades de emprego na era da inteligência digital, o uso da IA na procura de emprego e em entrevistas, e a inovação tecnológica e a prática do empreendedorismo, num conteúdo que aliou visão de futuro e utilidade prática, ajudando os estudantes a acompanhar as últimas tendências do mercado.",
            "Na sessão interactiva, os estudantes colocaram perguntas com entusiasmo, trocando impressões com os oradores sobre a elaboração de currículos, a preparação de entrevistas e a escolha de percursos profissionais, num ambiente caloroso.",
            "A organização encorajou os estudantes a abraçar proactivamente as oportunidades da era da inteligência digital, a planear atempadamente as suas carreiras e a elevar a literacia digital e a competitividade global, anunciando a realização de novas edições da iniciativa para apoiar o emprego de qualidade e o crescimento dos jovens de Macau.",
        ],
     }},
    {"date": "2026-03-28", "slug": "hainan-ftp-seminar-yang-cheng",
     "category": {"zh-TW": "智庫交流", "zh-CN": "智库交流", "en": "Think Tank Exchange", "pt": "Intercâmbio de Think Tanks"},
     "title": {"zh-TW": "會長楊誠出席「香港、澳門經驗對海南自貿港建設的借鑑與啟示」研討會",
               "zh-CN": "会长杨诚出席「香港、澳门经验对海南自贸港建设的借鉴与启示」研讨会",
               "en": "President Yang Cheng Attends Seminar on \"Lessons from the Hong Kong and Macao Experience for Hainan Free Trade Port Development\"",
               "pt": "Presidente Yang Cheng Participa em Seminário sobre as Experiências de Hong Kong e Macau para a Construção do Porto de Livre Comércio de Hainan"},
     "excerpt": {"zh-TW": "會長楊誠應邀出席國務院發展研究中心港澳研究所在京舉辦的海南自貿港研討會，與京港澳專家共商自貿港法治建設與風險防控。",
                 "zh-CN": "会长杨诚应邀出席国务院发展研究中心港澳研究所在京举办的海南自贸港研讨会，与京港澳专家共商自贸港法治建设与风险防控。",
                 "en": "President Yang Cheng joined experts from Beijing, Hong Kong and Macao at a seminar hosted by the Hong Kong and Macao Research Institute of the State Council's Development Research Center, discussing rule-of-law development and risk control for the Hainan Free Trade Port.",
                 "pt": "O Presidente Yang Cheng participou, em Pequim, num seminário sobre o Porto de Livre Comércio de Hainan organizado pelo Instituto de Investigação de Hong Kong e Macau do Centro de Investigação do Desenvolvimento do Conselho de Estado."},
     "source": {"name": {"zh-TW": "國務院發展研究中心港澳研究所", "zh-CN": "国务院发展研究中心港澳研究所",
                         "en": "Hong Kong and Macao Research Institute, Development Research Center of the State Council",
                         "pt": "Instituto de Investigação de Hong Kong e Macau do Centro de Investigação do Desenvolvimento do Conselho de Estado"},
                "url": "https://www.hkong.cn/2026/0330/59545.shtml"},
     "body": {
        "zh-TW": [
            "由國務院發展研究中心港澳研究所主辦的「香港、澳門經驗對海南自貿港建設的借鑑與啟示」研討會於2026年3月28日在北京舉行，港澳研究所所長畢雁英主持會議。本會會長、澳門理工大學客座教授楊誠應邀出席並參與研討。",
            "與會專家包括香港立法會議員范凱杰、香港城市大學王江雨教授、澳門發展策略研究中心秘書長陳志峰、清華大學國家治理研究院院長王振民、中國國際貿易學會會長金旭等，圍繞海南自貿港法治體系構建、貿易投資自由化便利化、現代服務業培育、跨境金融創新、風險防控與治理效能等議題深入交流。",
            "楊誠結合澳門自由港與單獨關稅區的實踐經驗，就海南自貿港封關運作後的制度銜接與風險防控提出建議，並表示澳門可在旅遊休閒、會展商貿、中醫藥等領域與海南加強合作，實現經驗共享與優勢互補。",
            "是次研討會體現了本會在國家重大戰略議題上的智庫參與。本會將持續關注海南自貿港建設進程，為澳門更好融入國家發展大局建言獻策。",
        ],
        "zh-CN": [
            "由国务院发展研究中心港澳研究所主办的「香港、澳门经验对海南自贸港建设的借鉴与启示」研讨会于2026年3月28日在北京举行，港澳研究所所长毕雁英主持会议。本会会长、澳门理工大学客座教授杨诚应邀出席并参与研讨。",
            "与会专家包括香港立法会议员范凯杰、香港城市大学王江雨教授、澳门发展策略研究中心秘书长陈志峰、清华大学国家治理研究院院长王振民、中国国际贸易学会会长金旭等，围绕海南自贸港法治体系构建、贸易投资自由化便利化、现代服务业培育、跨境金融创新、风险防控与治理效能等议题深入交流。",
            "杨诚结合澳门自由港与单独关税区的实践经验，就海南自贸港封关运作后的制度衔接与风险防控提出建议，并表示澳门可在旅游休闲、会展商贸、中医药等领域与海南加强合作，实现经验共享与优势互补。",
            "是次研讨会体现了本会在国家重大战略议题上的智库参与。本会将持续关注海南自贸港建设进程，为澳门更好融入国家发展大局建言献策。",
        ],
        "en": [
            "The seminar \"Hong Kong and Macao Experience: Lessons and Inspiration for the Development of the Hainan Free Trade Port,\" organised by the Hong Kong and Macao Research Institute of the Development Research Center of the State Council, was held in Beijing on 28 March 2026, chaired by the Institute's Director Bi Yanying. MFTEDA President Yang Cheng, who is also a guest professor at the Macao Polytechnic University, attended upon invitation and took part in the discussions.",
            "Participants included Hong Kong Legislative Council member Fan Kaijie, Professor Wang Jiangyu of City University of Hong Kong, Chen Zhifeng, Secretary-General of the Macao Development Strategy Research Centre, Wang Zhenmin, Dean of the Institute for State Governance at Tsinghua University, and Jin Xu, President of the China Association of International Trade. They held in-depth exchanges on topics including the construction of the rule-of-law system of the Hainan Free Trade Port, trade and investment liberalisation and facilitation, cultivation of modern service industries, cross-border financial innovation, risk prevention and control, and governance effectiveness.",
            "Drawing on Macao's practical experience as a free port and a separate customs territory, Yang Cheng offered suggestions on institutional alignment and risk prevention following the island-wide independent customs operation of the Hainan Free Trade Port, noting that Macao could strengthen cooperation with Hainan in areas such as tourism and leisure, MICE and commerce, and traditional Chinese medicine, achieving experience sharing and complementarity of strengths.",
            "The seminar reflects MFTEDA's think-tank participation in issues of major national strategy. MFTEDA will continue to follow the development of the Hainan Free Trade Port and offer advice and recommendations for Macao's better integration into the nation's overall development.",
        ],
        "pt": [
            "O seminário «As Experiências de Hong Kong e Macau como Referência e Inspiração para a Construção do Porto de Livre Comércio de Hainan», organizado pelo Instituto de Investigação de Hong Kong e Macau do Centro de Investigação do Desenvolvimento do Conselho de Estado, realizou-se em Pequim a 28 de março de 2026, sob a presidência da directora do Instituto, Bi Yanying. O Presidente da MFTEDA e professor convidado da Universidade Politécnica de Macau, Yang Cheng, participou no evento a convite.",
            "Entre os participantes estiveram o deputado do Conselho Legislativo de Hong Kong Fan Kaijie, o professor Wang Jiangyu da Universidade da Cidade de Hong Kong, Chen Zhifeng, secretário-geral do Centro de Investigação de Estratégia de Desenvolvimento de Macau, Wang Zhenmin, director do Instituto de Governação Nacional da Universidade Tsinghua, e Jin Xu, presidente da Associação Chinesa de Comércio Internacional, que trocaram impressões de forma aprofundada sobre a construção do sistema jurídico do Porto de Livre Comércio de Hainan, a liberalização e facilitação do comércio e do investimento, o fomento dos serviços modernos, a inovação financeira transfronteiriça, a prevenção e o controlo de riscos e a eficácia da governação.",
            "Com base na experiência prática de Macau enquanto porto franco e território aduaneiro separado, Yang Cheng apresentou sugestões sobre a articulação institucional e a prevenção de riscos após o início da operação aduaneira independente do Porto de Livre Comércio de Hainan, referindo que Macau pode reforçar a cooperação com Hainan nas áreas do turismo e lazer, das convenções, exposições e comércio, e da medicina tradicional chinesa, concretizando a partilha de experiências e a complementaridade de vantagens.",
            "O seminário reflecte a participação da MFTEDA, enquanto think tank, nos grandes temas da estratégia nacional. A MFTEDA continuará a acompanhar a construção do Porto de Livre Comércio de Hainan e a apresentar propostas para uma melhor integração de Macau no desenvolvimento global do país.",
        ],
     }},
    {"date": "2025-12-06", "slug": "zhongshan-torch-overseas-talent-workstation",
     "category": {"zh-TW": "合作簽約", "zh-CN": "合作签约", "en": "Cooperation Signing", "pt": "Assinatura de Cooperação"},
     "title": {"zh-TW": "本會與中山火炬高新區簽訂海外人才工作站合作框架協議",
               "zh-CN": "本会与中山火炬高新区签订海外人才工作站合作框架协议",
               "en": "MFTEDA Signs Overseas Talent Workstation Framework Agreement with Zhongshan Torch Hi-Tech Zone",
               "pt": "MFTEDA Assina Acordo-Quadro para Estação de Trabalho de Talentos Ultramarinos com a Zona de Alta Tecnologia Torch de Zhongshan"},
     "excerpt": {"zh-TW": "本會與中山火炬高新區簽訂海外人才工作站合作框架協議，並協辦澳中青年人才交流沙龍，拓寬國際化引才渠道。",
                 "zh-CN": "本会与中山火炬高新区签订海外人才工作站合作框架协议，并协办澳中青年人才交流沙龙，拓宽国际化引才渠道。",
                 "en": "MFTEDA signed a framework agreement with Zhongshan Torch Hi-Tech Zone to jointly build an overseas talent workstation, and co-organised a Macao–Zhongshan youth talent exchange salon, broadening channels for international talent recruitment.",
                 "pt": "A MFTEDA assinou um acordo-quadro de cooperação com a Zona de Alta Tecnologia Torch de Zhongshan para a construção conjunta de uma estação de trabalho de talentos ultramarinos, alargando os canais internacionais de captação de talentos."},
     "source": {"name": {"zh-TW": "中山網", "zh-CN": "中山网", "en": "Zhongshan News (zsnews.cn)", "pt": "Zhongshan News (zsnews.cn)"},
                "url": "http://www.zsnews.cn/town/index/view/cateid/1202/id/765538.html"},
     "body": {
        "zh-TW": [
            "「中山火炬人才『創享薈』——『澳中聚英才·青年創未來』澳中青年人才交流沙龍」於2025年12月6日在中國中山留學人員創業園舉行。活動由火炬高新區黨建辦指導，火炬高新區創新創業服務中心、火炬人才港主辦，本會與澳門學人發展協會協辦，吸引兩地逾50名企業家、青年人才及碩博代表參加。",
            "活動上，火炬高新區創新創業服務中心與本會簽訂海外人才工作站合作框架協議。根據協議，雙方將在人才宣傳推介、高層次人才引薦、交流活動組織及聯絡平台搭建等方面開展合作，共同拓寬國際化引才渠道。",
            "沙龍期間，澳門青年人才進行了AI賦能中醫藥研發、物聯網安全通信、空中操作系統三項創新成果路演，展示澳門青年的科研實力與創業活力；與會代表其後參觀了國家健康基地、大灣區檢科院及光大光學，實地了解火炬高新區的產業生態與創新平台。",
            "火炬高新區2025年人才工作年度總結確認，火炬人才港與本會共建海外人才工作站，標誌着雙方人才合作邁入機制化新階段。本會將繼續發揮橋樑作用，協助澳門青年人才把握大灣區發展機遇。",
        ],
        "zh-CN": [
            "「中山火炬人才『创享荟』——『澳中聚英才·青年创未来』澳中青年人才交流沙龙」于2025年12月6日在中国中山留学人员创业园举行。活动由火炬高新区党建办指导，火炬高新区创新创业服务中心、火炬人才港主办，本会与澳门学人发展协会协办，吸引两地逾50名企业家、青年人才及硕博代表参加。",
            "活动上，火炬高新区创新创业服务中心与本会签订海外人才工作站合作框架协议。根据协议，双方将在人才宣传推介、高层次人才引荐、交流活动组织及联络平台搭建等方面开展合作，共同拓宽国际化引才渠道。",
            "沙龙期间，澳门青年人才进行了AI赋能中医药研发、物联网安全通信、空中操作系统三项创新成果路演，展示澳门青年的科研实力与创业活力；与会代表其后参观了国家健康基地、大湾区检科院及光大光学，实地了解火炬高新区的产业生态与创新平台。",
            "火炬高新区2025年人才工作年度总结确认，火炬人才港与本会共建海外人才工作站，标志着双方人才合作迈入机制化新阶段。本会将继续发挥桥梁作用，协助澳门青年人才把握大湾区发展机遇。",
        ],
        "en": [
            "The Macao–Zhongshan Youth Talent Exchange Salon — \"Macao and Zhongshan Gathering Talent, Youth Creating the Future\" — was held on 6 December 2025 at the China Zhongshan Pioneer Park for Overseas Students. Guided by the Party Building Office of the Torch Hi-Tech Industrial Development Zone and hosted by the Zone's Innovation and Entrepreneurship Service Centre and the Torch Talent Hub, the event was co-organised by MFTEDA and the Macao Scholars Development Association, bringing together over 50 entrepreneurs, young talent and master's and doctoral representatives from both cities.",
            "At the event, the Torch Hi-Tech Zone Innovation and Entrepreneurship Service Centre and MFTEDA signed a framework cooperation agreement on an overseas talent workstation. Under the agreement, the two sides will cooperate in talent promotion and publicity, referral of high-level talent, organisation of exchange activities and the building of liaison platforms, jointly broadening channels for international talent recruitment.",
            "During the salon, young Macao talent presented three innovation roadshows — AI-empowered traditional Chinese medicine R&D, secure IoT communications, and an aerial operating system — demonstrating the research strength and entrepreneurial vitality of Macao's youth. Participants later visited the National Health Technology Park, the Greater Bay Area Academy of Inspection and Quarantine Science, and Guangda Optics, gaining first-hand insight into the industrial ecosystem and innovation platforms of the Torch Hi-Tech Zone.",
            "The Torch Hi-Tech Zone's 2025 annual review of talent work confirmed that the Torch Talent Hub and MFTEDA are jointly building an overseas talent workstation, marking a new, institutionalised stage in bilateral talent cooperation. MFTEDA will continue to serve as a bridge, helping Macao's young talent seize the development opportunities of the Greater Bay Area.",
        ],
        "pt": [
            "O Salão de Intercâmbio de Jovens Talentos Macau-Zhongshan «Macau e Zhongshan Reúnem Talentos, a Juventude Cria o Futuro» realizou-se a 6 de dezembro de 2025 no Parque de Incubação para Estudantes Regressados de Zhongshan, China. Orientado pelo Gabinete de Construção do Partido da Zona de Desenvolvimento Industrial de Alta Tecnologia Torch e organizado pelo Centro de Serviços de Inovação e Empreendedorismo da Zona e pelo Pólo de Talentos Torch, o evento contou com a coorganização da MFTEDA e da Associação de Desenvolvimento dos Académicos de Macau, reunindo mais de 50 empresários, jovens talentos e representantes de mestres e doutorados das duas cidades.",
            "No evento, o Centro de Serviços de Inovação e Empreendedorismo da Zona de Alta Tecnologia Torch e a MFTEDA assinaram um acordo-quadro de cooperação para uma estação de trabalho de talentos ultramarinos. Nos termos do acordo, as duas partes irão cooperar na divulgação e promoção de talentos, na indicação de talentos de alto nível, na organização de actividades de intercâmbio e na construção de plataformas de ligação, alargando em conjunto os canais internacionais de captação de talentos.",
            "Durante o salão, jovens talentos de Macau apresentaram três projectos inovadores — investigação e desenvolvimento de medicina tradicional chinesa potenciada por inteligência artificial, comunicações seguras para a Internet das Coisas e um sistema operativo aéreo — demonstrando a capacidade científica e a vitalidade empreendedora da juventude de Macau. Os participantes visitaram ainda a Base Nacional de Saúde, a Academia de Ciências de Inspecção e Quarentena da Grande Baía e a Guangda Optics, conhecendo de perto o ecossistema industrial e as plataformas de inovação da Zona Torch.",
            "O balanço anual de 2025 do trabalho de talentos da Zona de Alta Tecnologia Torch confirmou que o Pólo de Talentos Torch e a MFTEDA estão a construir em conjunto uma estação de trabalho de talentos ultramarinos, assinalando uma nova fase de institucionalização da cooperação em matéria de talentos. A MFTEDA continuará a desempenhar o papel de ponte, ajudando os jovens talentos de Macau a aproveitar as oportunidades de desenvolvimento da Grande Baía.",
        ],
     }},
    {"date": "2025-12-03", "slug": "zhongshan-ql-visit-macao-doctoral-thinktank",
     "category": {"zh-TW": "僑務交流", "zh-CN": "侨务交流", "en": "Overseas Chinese Affairs Exchange", "pt": "Intercâmbio dos Assuntos dos Chineses Ultramarinos"},
     "title": {"zh-TW": "中山市僑聯拜訪澳門博士智庫　會長楊誠出席交流座談",
               "zh-CN": "中山市侨联拜访澳门博士智库　会长杨诚出席交流座谈",
               "en": "Zhongshan Federation of Returned Overseas Chinese Visits Macao Doctoral Think Tank; President Yang Cheng Attends Exchange Seminar",
               "pt": "Federação dos Chineses Ultramarinos Regressados de Zhongshan Visita o Think Tank dos Doutorados de Macau com a Presença do Presidente Yang Cheng"},
     "excerpt": {"zh-TW": "中山市僑聯主席劉志巍率隊拜訪澳門博士智庫，雙方就僑界人才交流與大灣區人才高地建設達成合作共識，本會會長楊誠出席座談。",
                 "zh-CN": "中山市侨联主席刘志巍率队拜访澳门博士智库，双方就侨界人才交流与大湾区人才高地建设达成合作共识，本会会长杨诚出席座谈。",
                 "en": "A delegation of the Zhongshan Federation of Returned Overseas Chinese visited the Macao Doctoral Think Tank; the two sides reached consensus on talent exchange cooperation, with MFTEDA President Yang Cheng in attendance.",
                 "pt": "Uma delegação da Federação dos Chineses Ultramarinos Regressados de Zhongshan visitou o Think Tank dos Doutorados de Macau, tendo as duas partes chegado a um consenso de cooperação em matéria de intercâmbio de talentos, com a presença do Presidente da MFTEDA, Yang Cheng."},
     "source": {"name": {"zh-TW": "廣東省歸國華僑聯合會", "zh-CN": "广东省归国华侨联合会",
                         "en": "Guangdong Federation of Returned Overseas Chinese",
                         "pt": "Federação dos Chineses Ultramarinos Regressados de Guangdong"},
                "url": "http://www.gdql.org.cn/dsdt/content/post_1312635.html"},
     "body": {
        "zh-TW": [
            "2025年12月3日，中山市僑聯主席劉志巍率隊赴澳門拜訪澳門博士智庫，雙方圍繞深化兩地僑界人才交流、精準對接僑智資源、助力粵港澳大灣區人才高地建設等議題舉行座談，並達成合作共識。",
            "澳門立法會議員黃家倫、澳門博士智庫主席鄧偉強在座談中表示，期望發揮智庫的橋樑紐帶作用，推動澳門科研人才與中山產業需求精準對接，促進兩地人才、項目與資源的雙向流動。本會會長楊誠以澳門博士智庫副理事長身份出席座談。",
            "劉志巍介紹了中山市僑聯在聯繫服務僑界人才方面的工作，並邀請澳門人才參加第四期「雁南歸」僑界引才活動，期望藉此吸引更多海外高層次人才到中山創新創業。",
            "雙方一致認為，中山與澳門地緣相近、人緣相親，在人才交流與產業合作方面潛力巨大，今後將建立常態化聯絡機制，共同為粵港澳大灣區高質量發展貢獻僑界力量。",
        ],
        "zh-CN": [
            "2025年12月3日，中山市侨联主席刘志巍率队赴澳门拜访澳门博士智库，双方围绕深化两地侨界人才交流、精准对接侨智资源、助力粤港澳大湾区人才高地建设等议题举行座谈，并达成合作共识。",
            "澳门立法会议员黄家伦、澳门博士智库主席邓伟强在座谈中表示，期望发挥智库的桥梁纽带作用，推动澳门科研人才与中山产业需求精准对接，促进两地人才、项目与资源的双向流动。本会会长杨诚以澳门博士智库副理事长身份出席座谈。",
            "刘志巍介绍了中山市侨联在联系服务侨界人才方面的工作，并邀请澳门人才参加第四期「雁南归」侨界引才活动，期望借此吸引更多海外高层次人才到中山创新创业。",
            "双方一致认为，中山与澳门地缘相近、人缘相亲，在人才交流与产业合作方面潜力巨大，今后将建立常态化联络机制，共同为粤港澳大湾区高质量发展贡献侨界力量。",
        ],
        "en": [
            "On 3 December 2025, Liu Zhiwei, Chairman of the Zhongshan Federation of Returned Overseas Chinese, led a delegation to Macao to visit the Macao Doctoral Think Tank. The two sides held a seminar on deepening exchanges among overseas-Chinese talent of the two cities, precisely aligning overseas Chinese intellectual resources, and contributing to the building of a talent highland in the Guangdong–Hong Kong–Macao Greater Bay Area, reaching a consensus on cooperation.",
            "Macao Legislative Assembly member Vong Ka Lon and Tang Wai Keong, Chairman of the Macao Doctoral Think Tank, expressed the hope that the think tank would serve as a bridge, connecting Macao's research talent with Zhongshan's industrial needs and promoting two-way flows of talent, projects and resources. MFTEDA President Yang Cheng attended the seminar in his capacity as Vice Chairman of the Macao Doctoral Think Tank.",
            "Liu Zhiwei introduced the Federation's work in connecting and serving overseas-Chinese talent, and invited Macao talent to take part in the fourth \"Yan Nan Gui\" talent recruitment programme, hoping to attract more high-level overseas talent to innovate and start businesses in Zhongshan.",
            "Both sides agreed that Zhongshan and Macao, close in geography and kinship, hold great potential for talent exchange and industrial cooperation, and that they would establish a regular liaison mechanism to jointly contribute to the high-quality development of the Greater Bay Area.",
        ],
        "pt": [
            "A 3 de dezembro de 2025, Liu Zhiwei, presidente da Federação dos Chineses Ultramarinos Regressados de Zhongshan, chefiou uma delegação a Macau para visitar o Think Tank dos Doutorados de Macau. As duas partes realizaram um colóquio sobre o aprofundamento dos intercâmbios de talentos dos círculos dos chineses ultramarinos das duas cidades, a articulação precisa dos recursos intelectuais desses círculos e o contributo para a construção de um pólo de talentos na Grande Baía Guangdong-Hong Kong-Macau, tendo chegado a um consenso de cooperação.",
            "O deputado à Assembleia Legislativa de Macau, Vong Ka Lon, e Tang Wai Keong, presidente do Think Tank dos Doutorados de Macau, manifestaram a expectativa de que o think tank desempenhe o papel de ponte, promovendo a articulação entre os talentos científicos de Macau e as necessidades industriais de Zhongshan e o fluxo bidireccional de talentos, projectos e recursos. O Presidente da MFTEDA, Yang Cheng, participou no colóquio na qualidade de vice-presidente do Think Tank dos Doutorados de Macau.",
            "Liu Zhiwei apresentou o trabalho da Federação na ligação e no apoio aos talentos dos círculos dos chineses ultramarinos e convidou os talentos de Macau a participarem na quarta edição da actividade de captação de talentos «Yan Nan Gui», com a expectativa de atrair mais talentos de alto nível do estrangeiro para inovarem e empreenderem em Zhongshan.",
            "As duas partes reconheceram que Zhongshan e Macau, próximas na geografia e nos laços humanos, têm enorme potencial de cooperação no intercâmbio de talentos e na indústria, acordando estabelecer um mecanismo de ligação regular para contribuírem em conjunto para o desenvolvimento de alta qualidade da Grande Baía.",
        ],
     }},
    {"date": "2025-11-08", "slug": "anti-war-80th-anniversary-lecture",
     "category": {"zh-TW": "愛國教育", "zh-CN": "爱国教育", "en": "Patriotic Education", "pt": "Educação Patriótica"},
     "title": {"zh-TW": "「崢嶸歲月愛國情——紀念抗戰勝利80週年」主題講座圓滿舉行",
               "zh-CN": "「峥嵘岁月爱国情——纪念抗战胜利80周年」主题讲座圆满举行",
               "en": "Themed Lecture \"Patriotic Sentiment Through Momentous Years — Marking the 80th Anniversary of Victory in the War of Resistance\" Successfully Held",
               "pt": "Realizada Palestra Temática «Sentimento Patriótico em Anos Memoráveis — 80.º Aniversário da Vitória da Guerra de Resistência»"},
     "excerpt": {"zh-TW": "本會與澳門愛國教育青年協會聯合主辦紀念抗戰勝利80週年主題講座，近百名市民與青年出席，重溫烽火歲月、傳承愛國精神。",
                 "zh-CN": "本会与澳门爱国教育青年协会联合主办纪念抗战胜利80周年主题讲座，近百名市民与青年出席，重温烽火岁月、传承爱国精神。",
                 "en": "MFTEDA and the Macao Patriotic Education Youth Association jointly hosted a themed lecture marking the 80th anniversary of the victory in the War of Resistance, attended by nearly one hundred citizens and young people.",
                 "pt": "A MFTEDA e a Associação de Educação Patriótica da Juventude de Macau coorganizaram uma palestra temática que assinalou o 80.º aniversário da vitória da Guerra de Resistência, com cerca de uma centena de participantes."},
     "source": {"name": {"zh-TW": "濠江日報", "zh-CN": "濠江日报", "en": "Hou Kong Daily", "pt": "Jornal Hou Kong"},
                "url": "https://houkongdailynews.com/instantNews/139207"},
     "body": {
        "zh-TW": [
            "由澳門財經科技與教育發展學會與澳門愛國教育青年協會聯合主辦、澳門文化發展基金資助的「崢嶸歲月愛國情——紀念中國人民抗日戰爭勝利80週年」主題講座，於2025年11月8日下午在澳門青年孵化中心會議廳圓滿舉行，吸引近百名市民與青年出席。",
            "講座邀請澳門大學憲法和基本法研究中心主任駱偉建、澳門理工大學音樂課程主任王曦、全國青聯澳區委員馬志容擔任主講嘉賓，分別從澳門抗戰歷史、抗戰文藝作品、愛國人物事蹟與青年培育等維度切入，帶領觀眾回望烽火歲月，感悟先輩的愛國情懷。",
            "活動設有歷史圖片展及紀錄片播放，並穿插抗戰歌曲教唱環節，現場氣氛熱烈；主辦方同時進行問卷調研及互動問答，深入了解青年對抗戰歷史的認知，增強活動的參與度與教育意義。",
            "主辦方表示，是次講座旨在引導澳門青年銘記歷史、珍愛和平，未來將持續打造兼具學術性與參與度的愛國主題活動，推動愛國愛澳教育深入人心。《澳門日報》亦於11月10日對活動作了報道。",
        ],
        "zh-CN": [
            "由澳门财经科技与教育发展学会与澳门爱国教育青年协会联合主办、澳门文化发展基金资助的「峥嵘岁月爱国情——纪念中国人民抗日战争胜利80周年」主题讲座，于2025年11月8日下午在澳门青年孵化中心会议厅圆满举行，吸引近百名市民与青年出席。",
            "讲座邀请澳门大学宪法和基本法研究中心主任骆伟建、澳门理工大学音乐课程主任王曦、全国青联澳区委员马志容担任主讲嘉宾，分别从澳门抗战历史、抗战文艺作品、爱国人物事迹与青年培育等维度切入，带领观众回望烽火岁月，感悟先辈的爱国情怀。",
            "活动设有历史图片展及纪录片播放，并穿插抗战歌曲教唱环节，现场气氛热烈；主办方同时进行问卷调研及互动问答，深入了解青年对抗战历史的认知，增强活动的参与度与教育意义。",
            "主办方表示，是次讲座旨在引导澳门青年铭记历史、珍爱和平，未来将持续打造兼具学术性与参与度的爱国主题活动，推动爱国爱澳教育深入人心。《澳门日报》亦于11月10日对活动作了报道。",
        ],
        "en": [
            "The themed lecture \"Patriotic Sentiment Through Momentous Years — Commemorating the 80th Anniversary of the Victory of the Chinese People's War of Resistance Against Japanese Aggression,\" jointly organised by MFTEDA and the Macao Patriotic Education Youth Association and funded by the Macao Cultural Development Fund, was successfully held on the afternoon of 8 November 2025 at the conference hall of the Macao Youth Incubation Centre, drawing nearly one hundred citizens and young people.",
            "The lecture featured Luo Weijian, Director of the Centre for Constitutional Law and Basic Law Studies of the University of Macau; Wang Xi, Programme Director of Music at the Macao Polytechnic University; and Ma Chi Iong, Macao member of the All-China Youth Federation, as keynote speakers. Drawing on Macao's wartime history, resistance-era literature and art, patriotic figures and youth development, they guided the audience in revisiting the years of conflict and appreciating the patriotic devotion of earlier generations.",
            "The event included a historical photo exhibition and documentary screenings, interspersed with the teaching and singing of wartime songs, creating a warm and lively atmosphere. A questionnaire survey and an interactive Q&A session were also conducted to better understand young people's knowledge of the history of the War of Resistance, enhancing both participation and educational value.",
            "The organisers stated that the lecture aimed to guide Macao's youth to remember history and cherish peace, and that they will continue to stage patriotic-themed activities combining academic rigour with public engagement, so that education in \"loving the country and loving Macao\" takes deeper root. The event was also covered by Macao Daily News on 10 November.",
        ],
        "pt": [
            "A palestra temática «Sentimento Patriótico em Anos Memoráveis — Comemoração do 80.º Aniversário da Vitória da Guerra de Resistência do Povo Chinês contra a Agressão Japonesa», coorganizada pela MFTEDA e pela Associação de Educação Patriótica da Juventude de Macau e financiada pelo Fundo de Desenvolvimento da Cultura de Macau, realizou-se com êxito na tarde de 8 de novembro de 2025, na sala de conferências do Centro de Incubação de Jovens de Macau, contando com a presença de cerca de uma centena de cidadãos e jovens.",
            "Foram oradores convidados Luo Weijian, director do Centro de Estudos da Lei Constitucional e da Lei Básica da Universidade de Macau; Wang Xi, coordenador do curso de Música da Universidade Politécnica de Macau; e Ma Chi Iong, membro de Macau da Federação da Juventude de Toda a China, que abordaram a história de Macau durante a Guerra de Resistência, as obras literárias e artísticas desse período, as figuras patrióticas e a formação dos jovens, conduzindo o público numa revisitação dos anos de guerra e do espírito patriótico das gerações anteriores.",
            "O evento incluiu uma exposição de fotografias históricas e a exibição de documentários, intercalados com o ensino e o canto colectivo de canções da época da guerra, num ambiente caloroso; foram ainda realizados um inquérito por questionário e uma sessão interactiva de perguntas e respostas, de modo a conhecer melhor a percepção dos jovens sobre a história da Guerra de Resistência, reforçando a participação e o valor pedagógico da actividade.",
            "Os organizadores afirmaram que a palestra visou levar os jovens de Macau a recordar a história e a valorizar a paz, e que continuarão a criar actividades patrióticas que aliem o rigor académico à participação, promovendo a educação do valor «amar a pátria e amar Macau». O evento foi também noticiado pelo Jornal Ou Mun a 10 de novembro.",
        ],
     }},
]

# 首頁三大重點領域卡片
focus_cards = [
    {"icon": "trending", "title": {"zh-TW": "現代金融", "zh-CN": "现代金融", "en": "Modern Finance", "pt": "Finanças Modernas"},
     "description": {"zh-TW": "推動金融科技創新與跨境金融合作", "zh-CN": "推动金融科技创新与跨境金融合作", "en": "Driving fintech innovation and cross-border financial cooperation", "pt": "Impulsionando inovação fintech e cooperação financeira transfronteiriça"}},
    {"icon": "globe", "title": {"zh-TW": "數字經濟", "zh-CN": "数字经济", "en": "Digital Economy", "pt": "Economia Digital"},
     "description": {"zh-TW": "探索人工智能、電子商務與數字化轉型", "zh-CN": "探索人工智能、电子商务与数字化转型", "en": "Exploring AI, e-commerce, and digital transformation", "pt": "Explorando IA, comércio eletrónico e transformação digital"}},
    {"icon": "users", "title": {"zh-TW": "大灣區合作", "zh-CN": "大湾区合作", "en": "Greater Bay Area Cooperation", "pt": "Cooperação da Grande Baía"},
     "description": {"zh-TW": "促進區域融合與跨境合作", "zh-CN": "促进区域融合与跨境合作", "en": "Promoting regional integration and cross-border cooperation", "pt": "Promovendo integração regional e cooperação transfronteiriça"}},
]

# 出版物封面圖對應
book_covers = {"university": "book-university.webp", "community": "book-community.webp",
               "youth": "book-youth.webp", "supplement": "book-supplement.webp"}

# 語言切換器顯示名稱
languages = [
    {"code": "zh-TW", "label": "繁體中文", "flag": "🇲🇴"},
    {"code": "zh-CN", "label": "简体中文", "flag": "🇨🇳"},
    {"code": "en", "label": "English", "flag": "🇬🇧"},
    {"code": "pt", "label": "Português", "flag": "🇵🇹"},
]

content = {
    "languages": languages,
    "default_lang": "zh-TW",
    "site_name": "澳門財經科技與教育發展學會",
    "site_name_en": "Macao Financial Technology and Education Development Association",
    "site_url": "https://mfteda.org",
    "email": "mfteda2020@163.com",
    "social": {"facebook": "#", "linkedin": "#", "twitter": "#"},
    "partners_href": {
        "partner1": "https://www.dsedt.gov.mo",
        "partner2": "https://www.ipim.gov.mo",
        "partner3": "http://www.iolaw.cssn.cn",
        "partner4": "https://www.bjql.org.cn",
        "partner5": "https://www.bnu.edu.cn",
        "partner6": "https://www.gzhu.edu.cn",
        "partner7": "https://www.mpu.edu.mo",
        "partner8": "https://www.usj.edu.mo",
        "partner9": "https://www.jisu.edu.cn",
        "partner10": "http://macau-publish.com/",
        "partner11": "https://www.mmc.edu.mo",
        "partner12": "https://www.facebook.com/MacauLiveAssociation/",
    },
    "i18n": i18n,
    "insights": insights,
    "news": news,
    "focus_cards": focus_cards,
    "policies": policies,
    "book_covers": book_covers,
}

with open('content.json', 'w', encoding='utf-8') as f:
    json.dump(content, f, ensure_ascii=False, indent=2)
print('content.json written:', len(json.dumps(content, ensure_ascii=False)), 'chars')
