#!/usr/bin/env python3
"""Assemble content.json: i18n.json + insights articles + homepage focus cards."""
import json

i18n = json.load(open('.scrape/i18n.json', encoding='utf-8'))

# 新增「招商政策」導航頁（build.py PAGES 含 policy，nav 需有對應鍵）
for code, label in {"zh-TW": "招商政策", "zh-CN": "招商政策",
                    "en": "Investment Policies", "pt": "Políticas de Investimento"}.items():
    i18n[code]['nav']['policy'] = label

# 招商政策數據（region: macao / hengqin；繁中為母本，其他語言為對應譯文）
policies = [
    {"region": "macao", "year": "2025–2026",
     "title": {"zh-TW": "政府產業基金及科技成果轉化引導基金", "zh-CN": "政府产业基金及科技成果转化引导基金",
               "en": "Government Industrial Fund and Technology Achievement Transformation Guidance Fund",
               "pt": "Fundo Industrial do Governo e Fundo Orientador para a Transformação de Conquistas Científicas"},
     "summary": {"zh-TW": "政府牽頭設立產業基金與科技成果轉化引導基金，以「政府+民間共同投資」模式吸引高新科技企業及項目落戶澳門。",
                 "zh-CN": "政府牵头设立产业基金与科技成果转化引导基金，以「政府+民间共同投资」模式吸引高新科技企业及项目落户澳门。",
                 "en": "Government-led industrial fund and technology transformation guidance fund, attracting high-tech enterprises and projects to Macao through a \"government + private co-investment\" model.",
                 "pt": "Fundo industrial liderado pelo Governo e fundo orientador de transformação tecnológica, atraindo empresas e projetos de alta tecnologia para Macau através do modelo de \"coinvestimento governo + privado\"."},
     "url": "https://www.gov.mo/zh-hant/news/1191808/"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "澳門科技研發產業園", "zh-CN": "澳门科技研发产业园",
               "en": "Macao Science and Technology Research and Development Industrial Park",
               "pt": "Parque Industrial de Investigação e Desenvolvimento Tecnológico de Macau"},
     "summary": {"zh-TW": "聚焦生物醫藥、集成電路、數字科技、航天科技四大領域的科創園區，定位為內地優質科企出海陣地與海外前沿科技項目落戶服務站。",
                 "zh-CN": "聚焦生物医药、集成电路、数字科技、航天科技四大领域的科创园区，定位为内地优质科企出海阵地与海外前沿科技项目落户服务站。",
                 "en": "An innovation park focused on biomedicine, integrated circuits, digital technology and aerospace technology, serving as a launchpad for mainland tech firms going global and a landing base for overseas frontier projects.",
                 "pt": "Parque de inovação focado em biomedicina, circuitos integrados, tecnologia digital e aeroespacial, servindo de base para empresas tecnológicas do continente se internacionalizarem e para projetos estrangeiros se instalarem."},
     "url": "https://www.dsedt.gov.mo/zh_MO/web/public/pg_stipc"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "支持澳門首店經濟發展計劃", "zh-CN": "支持澳门首店经济发展计划",
               "en": "Programme for Supporting the Development of Macao First-Store Economy",
               "pt": "Programa de Apoio ao Desenvolvimento da Economia de Primeiras Lojas de Macau"},
     "summary": {"zh-TW": "向國際品牌及內地、港澳台品牌在澳門開設首間實體店提供啟動及經營開支資助，進駐指定社區設疊加資助。",
                 "zh-CN": "向国际品牌及内地、港澳台品牌在澳门开设首间实体店提供启动及经营开支资助，进驻指定社区设叠加资助。",
                 "en": "Subsidies for international brands and brands from the mainland, Hong Kong, Macao and Taiwan opening their first physical store in Macao, with additional support for designated communities.",
                 "pt": "Subsídios para marcas internacionais e do continente, Hong Kong, Macau e Taiwan abrirem a sua primeira loja física em Macau, com apoio adicional em comunidades designadas."},
     "url": "https://www.ipim.gov.mo/zh-hant/investment-promotion/programme-for-supporting-the-development-of-macao-first-store-economy"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "會議及展覽激勵計劃", "zh-CN": "会议及展览激励计划",
               "en": "MICE Incentive Measures", "pt": "Medidas de Incentivo a Convenções e Exposições"},
     "summary": {"zh-TW": "資助在澳門舉辦的會展活動，涵蓋澳門與橫琴「一會展兩地」模式，每項活動資助上限300萬澳門元。",
                 "zh-CN": "资助在澳门举办的会展活动，涵盖澳门与横琴「一会展两地」模式，每项活动资助上限300万澳门元。",
                 "en": "Funding for MICE events held in Macao, covering the \"one event, two venues\" model between Macao and Hengqin, up to MOP 3 million per event.",
                 "pt": "Financiamento de eventos MICE realizados em Macau, incluindo o modelo \"um evento, dois locais\" entre Macau e Hengqin, até 3 milhões de patacas por evento."},
     "url": "https://www.ipim.gov.mo/zh-hant/mice/the-incentive-measures/"},
    {"region": "macao", "year": "2026",
     "title": {"zh-TW": "澳門國際科技產業中心", "zh-CN": "澳门国际科技产业中心",
               "en": "Macao International Technology Industry Center",
               "pt": "Centro Internacional da Indústria Tecnológica de Macau"},
     "summary": {"zh-TW": "由經科局、科技基金、招商投資促進局共建的科企落戶載體，首批科技企業已進駐，同場啟動「澳門招商大使」計劃。",
                 "zh-CN": "由经科局、科技基金、招商投资促进局共建的科企落户载体，首批科技企业已进驻，同场启动「澳门招商大使」计划。",
                 "en": "A landing platform for tech enterprises jointly built by DSEDT, FDCT and IPIM, with the first batch of tech companies settled in, alongside the launch of the \"Macao Investment Promotion Ambassador\" programme.",
                 "pt": "Plataforma de instalação de empresas tecnológicas construída conjuntamente pela DSEDT, FDCT e IPIM, com a primeira leva de empresas já instalada, e lançamento do programa \"Embaixador de Promoção de Investimento de Macau\"."},
     "url": "https://www.gsef.gov.mo/zh/posts/11928"},
    {"region": "macao", "year": {"zh-TW": "長期", "zh-CN": "长期", "en": "Ongoing", "pt": "Contínuo"},
     "title": {"zh-TW": "投資者一站式服務", "zh-CN": "投资者一站式服务",
               "en": "One-Stop Service for Investors", "pt": "Serviço de Balcão Único para Investidores"},
     "summary": {"zh-TW": "招商投資促進局提供專人跟進落戶、協調成立公司手續等一站式服務。",
                 "zh-CN": "招商投资促进局提供专人跟进落户、协调成立公司手续等一站式服务。",
                 "en": "IPIM provides one-stop services including dedicated follow-up for investors and coordination of company incorporation procedures.",
                 "pt": "O IPIM oferece serviços de balcão único, incluindo acompanhamento personalizado e coordenação dos procedimentos de constituição de empresas."},
     "url": "https://www.gov.mo/zh-hant/services/ps-1417/"},
    {"region": "hengqin", "year": "2022起",
     "title": {"zh-TW": "企業所得稅15%優惠", "zh-CN": "企业所得税15%优惠",
               "en": "15% Corporate Income Tax Incentive", "pt": "Incentivo de Imposto sobre Rendimento Empresarial de 15%"},
     "summary": {"zh-TW": "設在橫琴深合區、以優惠目錄產業為主營業務並實質性運營的企業，減按15%徵收企業所得稅。",
                 "zh-CN": "设在横琴深合区、以优惠目录产业为主营业务并实质性运营的企业，减按15%征收企业所得税。",
                 "en": "Enterprises established in the Hengqin Cooperation Zone with substantive operations in encouraged industries enjoy a reduced 15% corporate income tax rate.",
                 "pt": "Empresas estabelecidas na Zona de Cooperação de Hengqin, com operações substantivas em indústrias incentivadas, beneficiam de uma taxa reduzida de 15% de imposto sobre o rendimento."},
     "url": "https://www.hengqin.gov.cn/lab/zccx/gjzc/content/post_3510124.html"},
    {"region": "hengqin", "year": "2026–2027",
     "title": {"zh-TW": "個人所得稅優惠延續（澳人澳稅）", "zh-CN": "个人所得税优惠延续（澳人澳税）",
               "en": "Extension of Individual Income Tax Incentives (Macao Tax for Macao Residents)",
               "pt": "Extensão dos Incentivos de Imposto sobre Rendimento Individual (Regime Fiscal de Macau para Residentes)"},
     "summary": {"zh-TW": "在合作區工作的境內外高端緊缺人才個稅超過15%部分免徵；澳門居民個稅超過澳門稅負部分免徵。財稅〔2026〕2號。",
                 "zh-CN": "在合作区工作的境内外高端紧缺人才个税超过15%部分免征；澳门居民个税超过澳门税负部分免征。财税〔2026〕2号。",
                 "en": "High-end and urgently needed talents working in the zone are exempt from individual income tax above 15%; Macao residents are exempt from tax exceeding the Macao tax burden. Caishui [2026] No. 2.",
                 "pt": "Talentos de alto nível e escassos que trabalhem na zona ficam isentos do imposto individual acima de 15%; residentes de Macau ficam isentos da parcela que exceda a carga fiscal de Macau. Caishui [2026] n.º 2."},
     "url": "https://www.hengqin.gov.cn/invest-hengqin/hqzx/news/zcdt/content/post_3878127.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "橫琴深合區產業發展規劃（2025–2029年）", "zh-CN": "横琴深合区产业发展规划（2025–2029年）",
               "en": "Hengqin Cooperation Zone Industrial Development Plan (2025–2029)",
               "pt": "Plano de Desenvolvimento Industrial da Zona de Cooperação de Hengqin (2025–2029)"},
     "summary": {"zh-TW": "構建科技研發和高端製造、中醫藥等澳門品牌工業、文旅會展商貿、現代金融四大產業片區，2029年「四新」產業增加值佔GDP約65%。",
                 "zh-CN": "构建科技研发和高端制造、中医药等澳门品牌工业、文旅会展商贸、现代金融四大产业片区，2029年「四新」产业增加值占GDP约65%。",
                 "en": "Builds four industrial clusters: tech R&D and high-end manufacturing, Macao-branded industries such as traditional Chinese medicine, cultural tourism, MICE and commerce, and modern finance; \"four new\" industries to account for about 65% of GDP by 2029.",
                 "pt": "Constrói quatro clusters industriais: I&D tecnológica e manufactura avançada, indústrias de marca de Macau como a medicina tradicional chinesa, turismo cultural, convenções e comércio, e finanças modernas; as \"quatro novas\" indústrias representarão cerca de 65% do PIB em 2029."},
     "url": "https://www.gdhmo.gov.cn/ygazdhzpt/content/post_97158.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "生物醫藥大健康產業扶持實施細則", "zh-CN": "生物医药大健康产业扶持实施细则",
               "en": "Implementation Rules for Supporting the Biomedicine and Big Health Industry",
               "pt": "Regras de Implementação de Apoio à Indústria Biomédica e de Grande Saúde"},
     "summary": {"zh-TW": "對標桿項目落戶、研發、臨床、註冊等環節給予專項資金支持，直接對接澳門「1+4」產業策略。",
                 "zh-CN": "对标杆项目落户、研发、临床、注册等环节给予专项资金支持，直接对接澳门「1+4」产业策略。",
                 "en": "Special funding for landmark projects covering settlement, R&D, clinical trials and registration, directly aligned with Macao's \"1+4\" industrial strategy.",
                 "pt": "Financiamento especial para projetos emblemáticos nas fases de instalação, I&D, ensaios clínicos e registo, alinhado com a estratégia industrial \"1+4\" de Macau."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/zcfg/gfxwj/content/post_3801996.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "金融產業高質量發展扶持辦法", "zh-CN": "金融产业高质量发展扶持办法",
               "en": "Measures for Supporting High-Quality Development of the Financial Industry",
               "pt": "Medidas de Apoio ao Desenvolvimento de Alta Qualidade da Indústria Financeira"},
     "summary": {"zh-TW": "對落戶合作區的金融機構、金融科技企業給予落戶獎勵、租金補貼、業務發展扶持，配合澳門現代金融產業發展。",
                 "zh-CN": "对落户合作区的金融机构、金融科技企业给予落户奖励、租金补贴、业务发展扶持，配合澳门现代金融产业发展。",
                 "en": "Settlement rewards, rent subsidies and business development support for financial institutions and fintech enterprises in the zone, complementing Macao's modern finance industry.",
                 "pt": "Prémios de instalação, subsídios de renda e apoio ao desenvolvimento de negócios para instituições financeiras e empresas fintech na zona, complementando a indústria financeira moderna de Macau."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/zcfg/gfxwj/content/post_3863296.html"},
    {"region": "hengqin", "year": "2024起",
     "title": {"zh-TW": "澳門青年創新創業扶持", "zh-CN": "澳门青年创新创业扶持",
               "en": "Support for Macao Youth Innovation and Entrepreneurship",
               "pt": "Apoio à Inovação e ao Empreendedorismo dos Jovens de Macau"},
     "summary": {"zh-TW": "經認定的澳門青年創業企業可享辦公場地租金扶持與創業獎勵，澳青創新創業基地享活動扶持。",
                 "zh-CN": "经认定的澳门青年创业企业可享办公场地租金扶持与创业奖励，澳青创新创业基地享活动扶持。",
                 "en": "Recognised Macao youth startups can receive office rent support and entrepreneurship rewards, with activity support for Macao youth innovation and entrepreneurship bases.",
                 "pt": "Startups de jovens de Macau reconhecidas podem beneficiar de apoio à renda de escritórios e prémios de empreendedorismo, com apoio a actividades nas bases de inovação e empreendedorismo juvenil."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/tzgg/gg/content/post_3834693.html"},
]


# 研究洞察 6 articles (titles/categories/excerpts per language, dates fixed)
insights = [
    {"date": "2026-03-15", "category": {"zh-TW": "數字經濟", "zh-CN": "数字经济", "en": "Digital Economy", "pt": "Economia Digital"},
     "title": {"zh-TW": "澳門數字經濟發展趨勢", "zh-CN": "澳门数字经济发展趋势", "en": "Digital Economy Trends in Macao", "pt": "Tendências da Economia Digital em Macau"},
     "excerpt": {"zh-TW": "分析澳門特區數字化轉型的機遇與挑戰", "zh-CN": "分析澳门特区数字化转型的机遇与挑战", "en": "Analysis of digital transformation opportunities and challenges in Macao SAR", "pt": "Análise de oportunidades e desafios da transformação digital na RAE de Macau"}},
    {"date": "2026-03-10", "category": {"zh-TW": "區域合作", "zh-CN": "区域合作", "en": "Regional Cooperation", "pt": "Cooperação Regional"},
     "title": {"zh-TW": "大灣區融合發展策略", "zh-CN": "大湾区融合发展策略", "en": "Greater Bay Area Integration Strategies", "pt": "Estratégias de Integração da Grande Baía"},
     "excerpt": {"zh-TW": "提升澳門在大灣區角色的政策建議", "zh-CN": "提升澳门在大湾区角色的政策建议", "en": "Policy recommendations for enhancing Macao's role in the Greater Bay Area", "pt": "Recomendações políticas para fortalecer o papel de Macau na Grande Baía"}},
    {"date": "2026-03-05", "category": {"zh-TW": "可持續金融", "zh-CN": "可持续金融", "en": "Sustainable Finance", "pt": "Finanças Sustentáveis"},
     "title": {"zh-TW": "ESG投資機遇", "zh-CN": "ESG投资机遇", "en": "ESG Investment Opportunities", "pt": "Oportunidades de Investimento ESG"},
     "excerpt": {"zh-TW": "探索可持續投資趨勢與綠色金融倡議", "zh-CN": "探索可持续投资趋势与绿色金融倡议", "en": "Exploring sustainable investment trends and green finance initiatives", "pt": "Explorando tendências de investimento sustentável e iniciativas de finanças verdes"}},
    {"date": "2026-02-28", "category": {"zh-TW": "現代金融", "zh-CN": "现代金融", "en": "Modern Finance", "pt": "Finanças Modernas"},
     "title": {"zh-TW": "人民幣國際化進展", "zh-CN": "人民币国际化进展", "en": "RMB Internationalization Progress", "pt": "Progresso da Internacionalização do RMB"},
     "excerpt": {"zh-TW": "人民幣跨境使用與金融合作的最新進展", "zh-CN": "人民币跨境使用与金融合作的最新进展", "en": "Latest developments in cross-border RMB usage and financial cooperation", "pt": "Últimos desenvolvimentos no uso transfronteiriço do RMB e cooperação financeira"}},
    {"date": "2026-02-20", "category": {"zh-TW": "創新", "zh-CN": "创新", "en": "Innovation", "pt": "Inovação"},
     "title": {"zh-TW": "文化與科技創新", "zh-CN": "文化与科技创新", "en": "Culture and Technology Innovation", "pt": "Inovação em Cultura e Tecnologia"},
     "excerpt": {"zh-TW": "科技如何改變澳門文化產業", "zh-CN": "科技如何改变澳门文化产业", "en": "How technology is transforming Macao's cultural industries", "pt": "Como a tecnologia está transformando as indústrias culturais de Macau"}},
    {"date": "2026-02-15", "category": {"zh-TW": "政策研究", "zh-CN": "政策研究", "en": "Policy Research", "pt": "Pesquisa Política"},
     "title": {"zh-TW": "自由貿易港監管最佳實踐", "zh-CN": "自由贸易港监管最佳实践", "en": "Free Trade Port Regulation Best Practices", "pt": "Melhores Práticas de Regulação de Porto de Livre Comércio"},
     "excerpt": {"zh-TW": "海關監管框架的國際比較", "zh-CN": "海关监管框架的国际比较", "en": "International comparison of customs regulation frameworks", "pt": "Comparação internacional de estruturas de regulação aduaneira"}},
]

# 首頁三大重點領域卡片
focus_cards = [
    {"icon": "trending", "title": {"zh-TW": "現代金融", "zh-CN": "现代金融", "en": "Modern Finance", "pt": "Finanças Modernas"},
     "description": {"zh-TW": "推動金融科技創新與跨境金融合作", "zh-CN": "推动金融科技创新与跨境金融合作", "en": "Driving fintech innovation and cross-border financial cooperation", "pt": "Impulsionando inovação fintech e cooperação financeira transfronteiriça"}},
    {"icon": "globe", "title": {"zh-TW": "數字經濟", "zh-CN": "数字经济", "en": "Digital Economy", "pt": "Economia Digital"},
     "description": {"zh-TW": "探索人工智能、電子商務與數字化轉型", "zh-CN": "探索人工智能、电子商务与数字化转型", "en": "Exploring AI, e-commerce, and digital transformation", "pt": "Explorando IA, comércio eletrónico e transformação digital"}},
    {"icon": "users", "title": {"zh-TW": "大灣區合作", "zh-CN": "大湾区合作", "en": "Greater Bay Area Cooperation", "pt": "Cooperação da Grande Baía"},
     "description": {"zh-TW": "促進區域融合與跨境合作", "zh-CN": "促进区域融合与跨境合作", "en": "Promoting regional integration and cross-border cooperation", "pt": "Promovendo integração regional e cooperação transfronteiriça"}},
]

# 出版物封面圖對應
book_covers = {"university": "book-university.webp", "community": "book-community.webp",
               "youth": "book-youth.webp", "supplement": "book-supplement.webp"}

# 語言切換器顯示名稱
languages = [
    {"code": "zh-TW", "label": "繁體中文", "flag": "🇲🇴"},
    {"code": "zh-CN", "label": "简体中文", "flag": "🇨🇳"},
    {"code": "en", "label": "English", "flag": "🇬🇧"},
    {"code": "pt", "label": "Português", "flag": "🇵🇹"},
]

content = {
    "languages": languages,
    "default_lang": "zh-TW",
    "site_name": "澳門財經科技與教育發展學會",
    "site_name_en": "Macao Financial Technology and Education Development Association",
    "site_url": "https://mfteda.org",
    "email": "mfteda2020@163.com",
    "social": {"facebook": "#", "linkedin": "#", "twitter": "#"},
    "partners_href": {
        "partner1": "https://www.dsedt.gov.mo",
        "partner2": "https://www.ipim.gov.mo",
        "partner3": "http://www.iolaw.cssn.cn",
        "partner4": "https://www.mpu.edu.mo",
        "partner5": "https://www.usj.edu.mo",
        "partner6": "https://www.jisu.edu.cn",
        "partner7": "#",
        "partner8": "https://www.facebook.com/MacauLiveAssociation/",
    },
    "i18n": i18n,
    "insights": insights,
    "focus_cards": focus_cards,
    "policies": policies,
    "book_covers": book_covers,
}

with open('content.json', 'w', encoding='utf-8') as f:
    json.dump(content, f, ensure_ascii=False, indent=2)
print('content.json written:', len(json.dumps(content, ensure_ascii=False)), 'chars')
