#!/usr/bin/env python3
"""Assemble content.json: i18n.json + insights articles + homepage focus cards."""
import json

i18n = json.load(open('.scrape/i18n.json', encoding='utf-8'))

# 新增「招商政策」導航頁（build.py PAGES 含 policy，nav 需有對應鍵）
for code, label in {"zh-TW": "招商政策", "zh-CN": "招商政策",
                    "en": "Investment Policies", "pt": "Políticas de Investimento"}.items():
    i18n[code]['nav']['policy'] = label

# 招商政策數據（region: macao / hengqin；繁中為母本，其他語言為對應譯文）
policies = [
    {"region": "macao", "year": "2025–2026",
     "title": {"zh-TW": "政府產業基金及科技成果轉化引導基金", "zh-CN": "政府产业基金及科技成果转化引导基金",
               "en": "Government Industrial Fund and Technology Achievement Transformation Guidance Fund",
               "pt": "Fundo Industrial do Governo e Fundo Orientador para a Transformação de Conquistas Científicas"},
     "summary": {"zh-TW": "政府牽頭設立產業基金與科技成果轉化引導基金，以「政府+民間共同投資」模式吸引高新科技企業及項目落戶澳門。",
                 "zh-CN": "政府牵头设立产业基金与科技成果转化引导基金，以「政府+民间共同投资」模式吸引高新科技企业及项目落户澳门。",
                 "en": "Government-led industrial fund and technology transformation guidance fund, attracting high-tech enterprises and projects to Macao through a \"government + private co-investment\" model.",
                 "pt": "Fundo industrial liderado pelo Governo e fundo orientador de transformação tecnológica, atraindo empresas e projetos de alta tecnologia para Macau através do modelo de \"coinvestimento governo + privado\"."},
     "url": "https://www.gov.mo/zh-hant/news/1191808/"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "澳門科技研發產業園", "zh-CN": "澳门科技研发产业园",
               "en": "Macao Science and Technology Research and Development Industrial Park",
               "pt": "Parque Industrial de Investigação e Desenvolvimento Tecnológico de Macau"},
     "summary": {"zh-TW": "聚焦生物醫藥、集成電路、數字科技、航天科技四大領域的科創園區，定位為內地優質科企出海陣地與海外前沿科技項目落戶服務站。",
                 "zh-CN": "聚焦生物医药、集成电路、数字科技、航天科技四大领域的科创园区，定位为内地优质科企出海阵地与海外前沿科技项目落户服务站。",
                 "en": "An innovation park focused on biomedicine, integrated circuits, digital technology and aerospace technology, serving as a launchpad for mainland tech firms going global and a landing base for overseas frontier projects.",
                 "pt": "Parque de inovação focado em biomedicina, circuitos integrados, tecnologia digital e aeroespacial, servindo de base para empresas tecnológicas do continente se internacionalizarem e para projetos estrangeiros se instalarem."},
     "url": "https://www.dsedt.gov.mo/zh_MO/web/public/pg_stipc"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "支持澳門首店經濟發展計劃", "zh-CN": "支持澳门首店经济发展计划",
               "en": "Programme for Supporting the Development of Macao First-Store Economy",
               "pt": "Programa de Apoio ao Desenvolvimento da Economia de Primeiras Lojas de Macau"},
     "summary": {"zh-TW": "向國際品牌及內地、港澳台品牌在澳門開設首間實體店提供啟動及經營開支資助，進駐指定社區設疊加資助。",
                 "zh-CN": "向国际品牌及内地、港澳台品牌在澳门开设首间实体店提供启动及经营开支资助，进驻指定社区设叠加资助。",
                 "en": "Subsidies for international brands and brands from the mainland, Hong Kong, Macao and Taiwan opening their first physical store in Macao, with additional support for designated communities.",
                 "pt": "Subsídios para marcas internacionais e do continente, Hong Kong, Macau e Taiwan abrirem a sua primeira loja física em Macau, com apoio adicional em comunidades designadas."},
     "url": "https://www.ipim.gov.mo/zh-hant/investment-promotion/programme-for-supporting-the-development-of-macao-first-store-economy"},
    {"region": "macao", "year": "2025",
     "title": {"zh-TW": "會議及展覽激勵計劃", "zh-CN": "会议及展览激励计划",
               "en": "MICE Incentive Measures", "pt": "Medidas de Incentivo a Convenções e Exposições"},
     "summary": {"zh-TW": "資助在澳門舉辦的會展活動，涵蓋澳門與橫琴「一會展兩地」模式，每項活動資助上限300萬澳門元。",
                 "zh-CN": "资助在澳门举办的会展活动，涵盖澳门与横琴「一会展两地」模式，每项活动资助上限300万澳门元。",
                 "en": "Funding for MICE events held in Macao, covering the \"one event, two venues\" model between Macao and Hengqin, up to MOP 3 million per event.",
                 "pt": "Financiamento de eventos MICE realizados em Macau, incluindo o modelo \"um evento, dois locais\" entre Macau e Hengqin, até 3 milhões de patacas por evento."},
     "url": "https://www.ipim.gov.mo/zh-hant/mice/the-incentive-measures/"},
    {"region": "macao", "year": "2026",
     "title": {"zh-TW": "澳門國際科技產業中心", "zh-CN": "澳门国际科技产业中心",
               "en": "Macao International Technology Industry Center",
               "pt": "Centro Internacional da Indústria Tecnológica de Macau"},
     "summary": {"zh-TW": "由經科局、科技基金、招商投資促進局共建的科企落戶載體，首批科技企業已進駐，同場啟動「澳門招商大使」計劃。",
                 "zh-CN": "由经科局、科技基金、招商投资促进局共建的科企落户载体，首批科技企业已进驻，同场启动「澳门招商大使」计划。",
                 "en": "A landing platform for tech enterprises jointly built by DSEDT, FDCT and IPIM, with the first batch of tech companies settled in, alongside the launch of the \"Macao Investment Promotion Ambassador\" programme.",
                 "pt": "Plataforma de instalação de empresas tecnológicas construída conjuntamente pela DSEDT, FDCT e IPIM, com a primeira leva de empresas já instalada, e lançamento do programa \"Embaixador de Promoção de Investimento de Macau\"."},
     "url": "https://www.gsef.gov.mo/zh/posts/11928"},
    {"region": "macao", "year": {"zh-TW": "長期", "zh-CN": "长期", "en": "Ongoing", "pt": "Contínuo"},
     "title": {"zh-TW": "投資者一站式服務", "zh-CN": "投资者一站式服务",
               "en": "One-Stop Service for Investors", "pt": "Serviço de Balcão Único para Investidores"},
     "summary": {"zh-TW": "招商投資促進局提供專人跟進落戶、協調成立公司手續等一站式服務。",
                 "zh-CN": "招商投资促进局提供专人跟进落户、协调成立公司手续等一站式服务。",
                 "en": "IPIM provides one-stop services including dedicated follow-up for investors and coordination of company incorporation procedures.",
                 "pt": "O IPIM oferece serviços de balcão único, incluindo acompanhamento personalizado e coordenação dos procedimentos de constituição de empresas."},
     "url": "https://www.gov.mo/zh-hant/services/ps-1417/"},
    {"region": "hengqin", "year": "2022起",
     "title": {"zh-TW": "企業所得稅15%優惠", "zh-CN": "企业所得税15%优惠",
               "en": "15% Corporate Income Tax Incentive", "pt": "Incentivo de Imposto sobre Rendimento Empresarial de 15%"},
     "summary": {"zh-TW": "設在橫琴深合區、以優惠目錄產業為主營業務並實質性運營的企業，減按15%徵收企業所得稅。",
                 "zh-CN": "设在横琴深合区、以优惠目录产业为主营业务并实质性运营的企业，减按15%征收企业所得税。",
                 "en": "Enterprises established in the Hengqin Cooperation Zone with substantive operations in encouraged industries enjoy a reduced 15% corporate income tax rate.",
                 "pt": "Empresas estabelecidas na Zona de Cooperação de Hengqin, com operações substantivas em indústrias incentivadas, beneficiam de uma taxa reduzida de 15% de imposto sobre o rendimento."},
     "url": "https://www.hengqin.gov.cn/lab/zccx/gjzc/content/post_3510124.html"},
    {"region": "hengqin", "year": "2026–2027",
     "title": {"zh-TW": "個人所得稅優惠延續（澳人澳稅）", "zh-CN": "个人所得税优惠延续（澳人澳税）",
               "en": "Extension of Individual Income Tax Incentives (Macao Tax for Macao Residents)",
               "pt": "Extensão dos Incentivos de Imposto sobre Rendimento Individual (Regime Fiscal de Macau para Residentes)"},
     "summary": {"zh-TW": "在合作區工作的境內外高端緊缺人才個稅超過15%部分免徵；澳門居民個稅超過澳門稅負部分免徵。財稅〔2026〕2號。",
                 "zh-CN": "在合作区工作的境内外高端紧缺人才个税超过15%部分免征；澳门居民个税超过澳门税负部分免征。财税〔2026〕2号。",
                 "en": "High-end and urgently needed talents working in the zone are exempt from individual income tax above 15%; Macao residents are exempt from tax exceeding the Macao tax burden. Caishui [2026] No. 2.",
                 "pt": "Talentos de alto nível e escassos que trabalhem na zona ficam isentos do imposto individual acima de 15%; residentes de Macau ficam isentos da parcela que exceda a carga fiscal de Macau. Caishui [2026] n.º 2."},
     "url": "https://www.hengqin.gov.cn/invest-hengqin/hqzx/news/zcdt/content/post_3878127.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "橫琴深合區產業發展規劃（2025–2029年）", "zh-CN": "横琴深合区产业发展规划（2025–2029年）",
               "en": "Hengqin Cooperation Zone Industrial Development Plan (2025–2029)",
               "pt": "Plano de Desenvolvimento Industrial da Zona de Cooperação de Hengqin (2025–2029)"},
     "summary": {"zh-TW": "構建科技研發和高端製造、中醫藥等澳門品牌工業、文旅會展商貿、現代金融四大產業片區，2029年「四新」產業增加值佔GDP約65%。",
                 "zh-CN": "构建科技研发和高端制造、中医药等澳门品牌工业、文旅会展商贸、现代金融四大产业片区，2029年「四新」产业增加值占GDP约65%。",
                 "en": "Builds four industrial clusters: tech R&D and high-end manufacturing, Macao-branded industries such as traditional Chinese medicine, cultural tourism, MICE and commerce, and modern finance; \"four new\" industries to account for about 65% of GDP by 2029.",
                 "pt": "Constrói quatro clusters industriais: I&D tecnológica e manufactura avançada, indústrias de marca de Macau como a medicina tradicional chinesa, turismo cultural, convenções e comércio, e finanças modernas; as \"quatro novas\" indústrias representarão cerca de 65% do PIB em 2029."},
     "url": "https://www.gdhmo.gov.cn/ygazdhzpt/content/post_97158.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "生物醫藥大健康產業扶持實施細則", "zh-CN": "生物医药大健康产业扶持实施细则",
               "en": "Implementation Rules for Supporting the Biomedicine and Big Health Industry",
               "pt": "Regras de Implementação de Apoio à Indústria Biomédica e de Grande Saúde"},
     "summary": {"zh-TW": "對標桿項目落戶、研發、臨床、註冊等環節給予專項資金支持，直接對接澳門「1+4」產業策略。",
                 "zh-CN": "对标杆项目落户、研发、临床、注册等环节给予专项资金支持，直接对接澳门「1+4」产业策略。",
                 "en": "Special funding for landmark projects covering settlement, R&D, clinical trials and registration, directly aligned with Macao's \"1+4\" industrial strategy.",
                 "pt": "Financiamento especial para projetos emblemáticos nas fases de instalação, I&D, ensaios clínicos e registo, alinhado com a estratégia industrial \"1+4\" de Macau."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/zcfg/gfxwj/content/post_3801996.html"},
    {"region": "hengqin", "year": "2025",
     "title": {"zh-TW": "金融產業高質量發展扶持辦法", "zh-CN": "金融产业高质量发展扶持办法",
               "en": "Measures for Supporting High-Quality Development of the Financial Industry",
               "pt": "Medidas de Apoio ao Desenvolvimento de Alta Qualidade da Indústria Financeira"},
     "summary": {"zh-TW": "對落戶合作區的金融機構、金融科技企業給予落戶獎勵、租金補貼、業務發展扶持，配合澳門現代金融產業發展。",
                 "zh-CN": "对落户合作区的金融机构、金融科技企业给予落户奖励、租金补贴、业务发展扶持，配合澳门现代金融产业发展。",
                 "en": "Settlement rewards, rent subsidies and business development support for financial institutions and fintech enterprises in the zone, complementing Macao's modern finance industry.",
                 "pt": "Prémios de instalação, subsídios de renda e apoio ao desenvolvimento de negócios para instituições financeiras e empresas fintech na zona, complementando a indústria financeira moderna de Macau."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/zcfg/gfxwj/content/post_3863296.html"},
    {"region": "hengqin", "year": "2024起",
     "title": {"zh-TW": "澳門青年創新創業扶持", "zh-CN": "澳门青年创新创业扶持",
               "en": "Support for Macao Youth Innovation and Entrepreneurship",
               "pt": "Apoio à Inovação e ao Empreendedorismo dos Jovens de Macau"},
     "summary": {"zh-TW": "經認定的澳門青年創業企業可享辦公場地租金扶持與創業獎勵，澳青創新創業基地享活動扶持。",
                 "zh-CN": "经认定的澳门青年创业企业可享办公场地租金扶持与创业奖励，澳青创新创业基地享活动扶持。",
                 "en": "Recognised Macao youth startups can receive office rent support and entrepreneurship rewards, with activity support for Macao youth innovation and entrepreneurship bases.",
                 "pt": "Startups de jovens de Macau reconhecidas podem beneficiar de apoio à renda de escritórios e prémios de empreendedorismo, com apoio a actividades nas bases de inovação e empreendedorismo juvenil."},
     "url": "https://www.hengqin.gov.cn/macao_zh_hans/zwgk/tzgg/gg/content/post_3834693.html"},
]


# 社評專欄：會長楊誠《澳門日報》社論（2026-09-30）
# column=True → 洞察列表頁頂部單獨「社評專欄」section；author/source → 詳情頁署名與原文出處
oped_article = {
    "date": "2026-09-30", "slug": "macao-strategic-pivot-shock-absorber", "column": True,
    "category": {"zh-TW": "社評專欄", "zh-CN": "社评专栏", "en": "Op-Ed", "pt": "Coluna de Opinião"},
    "title": {"zh-TW": "澳門立戰略支點　當開放大局的減震墊", "zh-CN": "澳门立战略支点　当开放大局的减震垫",
              "en": "Macao as a Strategic Pivot: A Shock Absorber for the Nation's Opening-Up",
              "pt": "Macau como Pivô Estratégico: Amortecedor da Abertura Nacional"},
    "excerpt": {"zh-TW": "澳門應在國家開放大局中擔當戰略支點，當好企業出海的“減震墊”，讓出海從驚險一躍變為一次有準備的軟着陸。",
                "zh-CN": "澳门应在国家开放大局中担当战略支点，当好企业出海的“减震垫”，让出海从惊险一跃变为一次有准备的软着陆。",
                "en": "Macao should serve as a strategic pivot in the nation's opening-up and a \"shock absorber\" for enterprises going global, turning a daring leap into a well-prepared soft landing.",
                "pt": "Macau deve assumir-se como pivô estratégico na abertura nacional e \"amortecedor\" das empresas que se internacionalizam, transformando um salto arriscado numa aterragem suave e preparada."},
    "author": {"name": {"zh-TW": "楊誠", "zh-CN": "杨诚", "en": "Yang Cheng", "pt": "Yang Cheng"},
               "title": {"zh-TW": "澳門財經科技與教育發展學會會長、澳門數字創新協會理事長",
                         "zh-CN": "澳门财经科技与教育发展学会会长、澳门数字创新协会理事长",
                         "en": "President of MFTEDA and Chairman of the Macao Digital Innovation Association",
                         "pt": "Presidente da MFTEDA e Presidente da Associação de Inovação Digital de Macau"}},
    "source": {"name": {"zh-TW": "澳門日報", "zh-CN": "澳门日报", "en": "Macao Daily News", "pt": "Jornal Ou Mun"},
               "url": "https://www.macaodaily.com/html/2026-09/30/content_1937056.htm"},
    "body": {
        "zh-TW": [
            "深夜，智能燈具企業負責人羅先生還在和團隊一起，跨時區與巴西客戶逐條敲定合同細節。產品拿到了意向訂單，可葡語合同怎麼簽、貨款怎麼結、標準怎麼認證、糾紛去哪裡仲裁──四道關卡，道道上寫着“不確定”三個字。這不是一家企業的遭遇，而是千千萬萬中國企業出海的共同寫照。",
            "八月十八日，《澳門特別行政區經濟和社會發展第三個五年規劃（二○二六至二○三○年）》正式公佈。這份主動對接國家“十五五”規劃、全文十篇三十六章的綱領性文件，回答的正是那位企業主的深夜之問，也是一道時代之問：小城市如何在國家大戰略中找到大位置？筆者認為，答案不在體量，而在定位──澳門當立的位置，是國家開放大局中的戰略支點；而支點發揮作用的方式，是當好企業出海的“減震墊”，讓出海不再是驚險一躍，而是一次有準備的軟着陸。",
            "關於澳門，坊間曾流行兩種看法：一種說，澳門不過是一座休閒旅遊城市，談何服務國家開放大局；另一種說，澳門要做平台，就得複製香港、新加坡的路。但只要看幾個事實，便知兩種說法都只說對了一半。國家賦予澳門“世界旅遊休閒中心”、“中國與葡語國家商貿合作服務平台”的定位，本身就內含着服務國家開放大局的使命；澳門作為自由港和單獨關稅區，四百多年中西交往史，沉澱下與葡語國家之間難以替代的制度接口。更難得的是社會共識──規劃編制歷時四十天公開諮詢，共收到一千七百一十六份、合共八千二百三十條意見，正面評價佔九成二。一條路徑能凝聚這樣的民意基礎，本身就說明它不是辦公室裡想出來的，而是從澳門的土壤裡長出來的。",
            "這塊“減震墊”的價值，在於把“一躍”變成“落地”，其功能體現在三個層面。一是把不確定性消化在專業服務裡：以法律、會計、金融、仲裁等配套，讓企業不必在陌生的規則環境中獨行；二是把風險處置留在體系之內：對已出海而遭遇硬着陸的企業，一企一策、專家陪跑，助其轉危為機──“減震墊”的作用，既在緩衝，也在回彈；三是把數字時代的合規門檻轉化為服務能力：善用科技手段與人工智能工具，協助企業構建合法合規的海外數字資產，減少數字領域的制度顛簸。中國企業出海，尤其是中小微企業，缺的從來不是勇氣，而是緩衝。",
            "更值得注意的是路徑的差異化。澳門主攻中小微企業與輕資產領域，以精準對接的平台、專項支持計劃和“以大帶小”的協作生態，把出海門檻降到最低，讓普惠紅利覆蓋最廣大的企業群體；同時，依託橫琴粵澳深度合作區的疊加優勢，穩妥探索境外合規數字資產業務，在科技研發產業園落成之前，先立起科技與金融雙輪驅動的架勢。這不是與香港、新加坡爭奪甚麼版圖，而是為國家開放版圖補上一塊空缺的拼圖──發揮澳門所長，服務國家所需。當然，一個支點要真正撬動國家開放的大局，必須把制度優勢轉譯為企業可感的服務，必須把差異化的定位守成難以替代的位置──兩個“必須”之間，正是“三五”規劃從藍圖走向現實的全部工作量。",
            "藍圖已繪就，關鍵在落實。“減震墊”不會自己長出來，沿着“事前、事中、事後”三個環節，政府、業界、學界各有功課。",
            "事前做緩衝，把不確定性消化在出發之前。建議政府盡快設立企業出海服務專班和一站式窗口，把葡語法律、會計、認證、仲裁整合為標準化的“出海服務包”，讓中小微企業尚未啟航，先看清航道上的暗礁──這是把澳門的制度稟賦，轉譯為國家高水平對外開放的可感服務。",
            "事中做承接，把個體經驗沉澱為公共資產。建議業界共建認證供應商庫與案例知識庫，以“以大帶小”的生態，讓先行者的經驗成為後來者的路基──一家企業踩過的坑，不該讓第二家再踩；這是把單個企業的試錯成本，轉化為國家開放體系的整體韌性。",
            "事後做回彈，把危機處置錘煉成一門學問。對已遭遇硬着陸的企業，一企一策、專家陪跑；學界則應把這些案例當真學問來做，多寫幾份管用的報告，多教幾位能用的學生，多陪幾家企業走過最難的那段路──統籌發展和安全，既要體現在國家的頂層設計裡，也要落到澳門這塊“減震墊”的每一根彈簧上。",
            "支點不是喊出來的，是一顆顆螺絲擰出來的；而擰螺絲的手，就在我們這一代澳門青年中間。",
            "行政主導體制給了澳門集中力量辦大事的效率，“一國兩制”給了澳門聯通中西的稟賦。習近平主席寄語澳門“登高望遠、海納百川、銳意進取”，這份囑託落到“三五”規劃，就是把澳門的發展命運與國家的開放大局緊緊聯在一起，讓“一國兩制”的制度優勢在服務國家所需中行穩致遠。這正是新時代“愛國愛澳”核心價值最具體的實踐。規劃的份量，不在十篇三十六章的字裡行間，而在千家萬戶企業的賬本上。歷史給予澳門的機遇，最終要落到那位深夜辦公室裡的企業主，能否睡個好覺上。",
            "澳門不必成為下一個香港或新加坡。但願五年之後，每一位深夜還在跨時區談生意的企業主，腳下都有一塊澳門造的“減震墊”──這，就是澳門對“國內國際循環相互促進”最樸素也最堅實的回答。",
        ],
        "zh-CN": [
            "深夜，智能灯具企业负责人罗先生还在和团队一起，跨时区与巴西客户逐条敲定合同细节。产品拿到了意向订单，可葡语合同怎么签、货款怎么结、标准怎么认证、纠纷去哪里仲裁──四道关卡，道道上写着“不确定”三个字。这不是一家企业的遭遇，而是千千万万中国企业出海的共同写照。",
            "八月十八日，《澳门特别行政区经济和社会发展第三个五年规划（二○二六至二○三○年）》正式公布。这份主动对接国家“十五五”规划、全文十篇三十六章的纲领性文件，回答的正是那位企业主的深夜之问，也是一道时代之问：小城市如何在国家大战略中找到大位置？笔者认为，答案不在体量，而在定位──澳门当立的位置，是国家开放大局中的战略支点；而支点发挥作用的方式，是当好企业出海的“减震垫”，让出海不再是惊险一跃，而是一次有准备的软着陆。",
            "关于澳门，坊间曾流行两种看法：一种说，澳门不过是一座休闲旅游城市，谈何服务国家开放大局；另一种说，澳门要做平台，就得复制香港、新加坡的路。但只要看几个事实，便知两种说法都只说对了一半。国家赋予澳门“世界旅游休闲中心”、“中国与葡语国家商贸合作服务平台”的定位，本身就内含着服务国家开放大局的使命；澳门作为自由港和单独关税区，四百多年中西交往史，沉淀下与葡语国家之间难以替代的制度接口。更难得的是社会共识──规划编制历时四十天公开咨询，共收到一千七百一十六份、合共八千二百三十条意见，正面评价占九成二。一条路径能凝聚这样的民意基础，本身就说明它不是办公室里想出来的，而是从澳门的土壤里长出来的。",
            "这块“减震垫”的价值，在于把“一跃”变成“落地”，其功能体现在三个层面。一是把不确定性消化在专业服务里：以法律、会计、金融、仲裁等配套，让企业不必在陌生的规则环境中独行；二是把风险处置留在体系之内：对已出海而遭遇硬着陆的企业，一企一策、专家陪跑，助其转危为机──“减震垫”的作用，既在缓冲，也在回弹；三是把数字时代的合规门槛转化为服务能力：善用科技手段与人工智能工具，协助企业构建合法合规的海外数字资产，减少数字领域的制度颠簸。中国企业出海，尤其是中小微企业，缺的从来不是勇气，而是缓冲。",
            "更值得注意的是路径的差异化。澳门主攻中小微企业与轻资产领域，以精准对接的平台、专项支持计划和“以大带小”的协作生态，把出海门槛降到最低，让普惠红利覆盖最广大的企业群体；同时，依托横琴粤澳深度合作区的叠加优势，稳妥探索境外合规数字资产业务，在科技研发产业园落成之前，先立起科技与金融双轮驱动的架势。这不是与香港、新加坡争夺甚么版图，而是为国家开放版图补上一块空缺的拼图──发挥澳门所长，服务国家所需。当然，一个支点要真正撬动国家开放的大局，必须把制度优势转译为企业可感的服务，必须把差异化的定位守成难以替代的位置──两个“必须”之间，正是“三五”规划从蓝图走向现实的全部工作量。",
            "蓝图已绘就，关键在落实。“减震垫”不会自己长出来，沿着“事前、事中、事后”三个环节，政府、业界、学界各有功课。",
            "事前做缓冲，把不确定性消化在出发之前。建议政府尽快设立企业出海服务专班和一站式窗口，把葡语法律、会计、认证、仲裁整合为标准化的“出海服务包”，让中小微企业尚未启航，先看清航道上的暗礁──这是把澳门的制度禀赋，转译为国家高水平对外开放的可感服务。",
            "事中做承接，把个体经验沉淀为公共资产。建议业界共建认证供应商库与案例知识库，以“以大带小”的生态，让先行者的经验成为后来者的路基──一家企业踩过的坑，不该让第二家再踩；这是把单个企业的试错成本，转化为国家开放体系的整体韧性。",
            "事后做回弹，把危机处置锤炼成一门学问。对已遭遇硬着陆的企业，一企一策、专家陪跑；学界则应把这些案例当真学问来做，多写几份管用的报告，多教几位能用的学生，多陪几家企业走过最难的那段路──统筹发展和安全，既要体现在国家的顶层设计里，也要落到澳门这块“减震垫”的每一根弹簧上。",
            "支点不是喊出来的，是一颗颗螺丝拧出来的；而拧螺丝的手，就在我们这一代澳门青年中间。",
            "行政主导体制给了澳门集中力量办大事的效率，“一国两制”给了澳门联通中西的禀赋。习近平主席寄语澳门“登高望远、海纳百川、锐意进取”，这份嘱托落到“三五”规划，就是把澳门的发展命运与国家的开放大局紧紧联在一起，让“一国两制”的制度优势在服务国家所需中行稳致远。这正是新时代“爱国爱澳”核心价值最具体的实践。规划的份量，不在十篇三十六章的字里行间，而在千家万户企业的账本上。历史给予澳门的机遇，最终要落到那位深夜办公室里的企业主，能否睡个好觉上。",
            "澳门不必成为下一个香港或新加坡。但愿五年之后，每一位深夜还在跨时区谈生意的企业主，脚下都有一块澳门造的“减震垫”──这，就是澳门对“国内国际循环相互促进”最朴素也最坚实的回答。",
        ],
        "en": [
            "Late at night, Mr. Lo, head of a smart-lighting company, was still working with his team across time zones, finalizing contract details line by line with a Brazilian client. The product had won a letter of intent—but how to sign a Portuguese-language contract, how to settle payment, how to certify standards, where to arbitrate disputes: four hurdles, each marked with the word \"uncertainty.\" This is not the story of one company; it is the shared portrait of countless Chinese enterprises going global.",
            "On August 18, the Third Five-Year Plan for Economic and Social Development of the Macao Special Administrative Region (2026–2030) was officially released. This programmatic document—ten parts and thirty-six chapters, proactively aligned with the nation's 15th Five-Year Plan—answers precisely that business owner's late-night question, and a question of our times: how can a small city find a big place in a national strategy? In my view, the answer lies not in size but in positioning. The position Macao should occupy is that of a strategic pivot in the nation's opening-up; and the way this pivot works is by serving as a \"shock absorber\" for enterprises going global—turning a daring leap into a well-prepared soft landing.",
            "Two views about Macao once circulated. One held that Macao is merely a leisure and tourism city, hardly fit to serve the nation's opening-up; the other held that to be a platform, Macao must copy the paths of Hong Kong or Singapore. A few facts show both are only half right. The nation's designation of Macao as a \"World Centre of Tourism and Leisure\" and a \"Commercial and Trade Cooperation Service Platform between China and Portuguese-speaking Countries\" inherently carries the mission of serving the nation's opening-up. As a free port and separate customs territory with over four centuries of East–West exchange, Macao has built an institutional interface with the Portuguese-speaking countries that is hard to replace. Rarer still is the social consensus: during forty days of public consultation on the plan, 1,716 submissions totalling 8,230 comments were received, 92 percent of them positive. A path that commands such popular support was not devised in an office—it grew out of Macao's own soil.",
            "The value of this \"shock absorber\" lies in turning a \"leap\" into a \"landing,\" and it functions on three levels. First, it digests uncertainty through professional services: legal, accounting, financial and arbitration support, so that enterprises need not navigate an unfamiliar rules environment alone. Second, it keeps risk resolution within the system: for companies that have gone global and suffered a hard landing, tailored \"one enterprise, one policy\" support and expert accompaniment help them turn crisis into opportunity—the absorber cushions, but it also rebounds. Third, it converts the compliance thresholds of the digital era into service capability: making good use of technology and artificial-intelligence tools to help enterprises build lawful, compliant overseas digital assets, reducing institutional turbulence in the digital realm. What Chinese enterprises going global—especially micro, small and medium-sized ones—have never lacked is courage; what they lack is cushioning.",
            "Equally notable is the differentiated path. Macao focuses on MSMEs and asset-light sectors, lowering entry barriers to a minimum through precisely matched platforms, dedicated support programmes and a \"big leading small\" ecosystem of collaboration, so that inclusive benefits reach the broadest business community. At the same time, drawing on the combined advantages of the Guangdong-Macao In-Depth Cooperation Zone in Hengqin, Macao prudently explores compliant offshore digital-asset businesses—putting in place the twin engines of technology and finance even before the science and technology R&D industrial park is completed. This is not a contest with Hong Kong or Singapore for territory, but the missing piece in the nation's map of opening-up: bringing what Macao does best to serve what the nation needs. Of course, for a pivot to truly move the whole of the nation's opening-up, institutional advantages must be translated into services enterprises can feel, and a differentiated position must be consolidated into an irreplaceable one—between these two \"musts\" lies the entire workload of turning the Third Five-Year Plan from blueprint into reality.",
            "The blueprint is drawn; delivery is the key. A \"shock absorber\" does not grow by itself. Across the three stages—before, during and after—government, industry and academia each have homework to do.",
            "Before departure: cushion, digesting uncertainty in advance. The government should promptly set up a dedicated task force and a one-stop window for enterprises going global, integrating Portuguese-language legal, accounting, certification and arbitration services into a standardized \"going-global service package,\" so that MSMEs can see the reefs along the route before they set sail. This translates Macao's institutional endowment into tangible services for the nation's high-standard opening-up.",
            "During the journey: carry through, turning individual experience into public assets. Industry should jointly build a pool of certified service providers and a case knowledge base, so that under a \"big leading small\" ecosystem the experience of pioneers becomes the roadbed for followers—a pit one company has fallen into should not trap a second. This converts the trial-and-error costs of individual firms into the overall resilience of the nation's opening-up system.",
            "After the event: rebound, honing crisis management into a discipline. For companies that have suffered a hard landing, apply \"one enterprise, one policy\" with expert accompaniment; academia should treat these cases as serious scholarship—writing more useful reports, training more capable students, and walking more companies through the hardest stretch of the road. Coordinating development and security must be reflected not only in the nation's top-level design, but also in every single spring of Macao's \"shock absorber.\"",
            "A pivot is not proclaimed; it is fastened screw by screw. And the hands tightening those screws are among this generation of Macao's young people.",
            "The executive-led system gives Macao the efficiency to concentrate resources on major undertakings; \"One Country, Two Systems\" gives Macao the endowment to connect China and the West. President Xi Jinping urged Macao to \"stand tall and look far, embrace all rivers, and forge ahead with resolve.\" Brought into the Third Five-Year Plan, this charge binds Macao's destiny tightly to the nation's opening-up, letting the institutional advantages of \"One Country, Two Systems\" go steady and far in serving the nation's needs. This is the most concrete practice of the core value of \"loving the country and loving Macao\" in the new era. The weight of the plan lies not in the lines of its ten parts and thirty-six chapters, but in the ledgers of thousands of enterprises. The opportunity history has given Macao must ultimately come down to whether that business owner in the late-night office can get a good night's sleep.",
            "Macao need not become the next Hong Kong or Singapore. May it be that, five years from now, every business owner negotiating across time zones late into the night has a Macao-made \"shock absorber\" beneath their feet. This is Macao's simplest and sturdiest answer to the \"mutual reinforcement of domestic and international circulation.\"",
        ],
        "pt": [
            "Já de madrugada, o senhor Lo, responsável por uma empresa de iluminação inteligente, continuava com a sua equipa, através de fusos horários, a ultimar ponto por ponto os detalhes do contrato com um cliente brasileiro. O produto tinha obtido uma encomenda de intenção, mas como assinar um contrato em português, como liquidar o pagamento, como certificar as normas, onde arbitrar os litígios — quatro barreiras, cada uma marcada pela palavra \"incerteza\". Não é a experiência de uma só empresa, mas o retrato comum de incontáveis empresas chinesas que se internacionalizam.",
            "A 18 de agosto, foi oficialmente publicado o Terceiro Plano Quinquenal de Desenvolvimento Económico e Social da Região Administrativa Especial de Macau (2026–2030). Este documento programático — dez partes e trinta e seis capítulos, que se articula proactivamente com o 15.º Plano Quinquenal nacional — responde precisamente à pergunta que inquietava aquele empresário de madrugada, e também a uma interrogação da época: como pode uma pequena cidade encontrar um grande lugar na estratégia nacional? Na minha opinião, a resposta não está na dimensão, mas no posicionamento: o lugar que Macau deve ocupar é o de pivô estratégico na abertura nacional; e a forma de este pivô actuar é servir de \"amortecedor\" para as empresas que se internacionalizam, fazendo com que a saída deixe de ser um salto arriscado e passe a ser uma aterragem suave e preparada.",
            "Sobre Macau circulavam duas opiniões. Uma dizia que Macau não passa de uma cidade de turismo e lazer, incapaz de servir a abertura nacional; outra dizia que, para ser plataforma, Macau tinha de copiar os caminhos de Hong Kong ou de Singapura. Basta olhar para alguns factos para ver que ambas acertam apenas metade. A posição atribuída pelo país a Macau de \"Centro Mundial de Turismo e Lazer\" e de \"Plataforma de Serviços para a Cooperação Comercial entre a China e os Países de Língua Portuguesa\" encerra em si a missão de servir a abertura nacional; enquanto porto franco e território aduaneiro separado, com mais de quatro séculos de contactos entre a China e o Ocidente, Macau sedimentou uma interface institucional com os países de língua portuguesa difícil de substituir. Mais raro ainda é o consenso social — a elaboração do plano incluiu quarenta dias de consulta pública, com 1.716 contributos e um total de 8.230 opiniões, 92% das quais favoráveis. Um caminho capaz de congregar tal base popular não foi imaginado num gabinete: cresceu do próprio solo de Macau.",
            "O valor deste \"amortecedor\" está em transformar o \"salto\" em \"aterragem\", e a sua função manifesta-se em três planos. Primeiro, digerir a incerteza através de serviços profissionais: com apoios jurídicos, contabilísticos, financeiros e de arbitragem, para que as empresas não caminhem sozinhas num ambiente de regras desconhecidas. Segundo, manter a gestão de riscos dentro do sistema: para as empresas já internacionalizadas que sofreram uma aterragem forçada, \"uma empresa, uma política\" e acompanhamento por especialistas, ajudando-as a transformar a crise em oportunidade — o \"amortecedor\" serve tanto para amortecer como para fazer ressaltar. Terceiro, converter os limiares de conformidade da era digital em capacidade de serviço: fazer bom uso da tecnologia e das ferramentas de inteligência artificial para ajudar as empresas a construir activos digitais no estrangeiro legais e conformes, reduzindo as turbulências institucionais no domínio digital. Às empresas chinesas que se internacionalizam — sobretudo às micro, pequenas e médias — nunca faltou coragem; falta-lhes amortecimento.",
            "Mais notável ainda é a diferenciação do percurso. Macau aposta nas micro, pequenas e médias empresas e nos sectores de activos leves, reduzindo ao mínimo as barreiras de entrada através de plataformas de articulação precisa, programas de apoio específicos e um ecossistema de colaboração em que \"os grandes levam os pequenos\", de modo a que os dividendos inclusivos cubram o mais amplo universo empresarial; ao mesmo tempo, apoiando-se nas vantagens sobrepostas da Zona de Cooperação Aprofundada Guangdong-Macau em Hengqin, explora com prudência negócios de activos digitais conformes no exterior, erguendo desde já — antes mesmo da conclusão do parque industrial de investigação e desenvolvimento tecnológico — a arquitectura de dupla propulsão da tecnologia e das finanças. Não se trata de disputar território com Hong Kong ou Singapura, mas de preencher uma peça que faltava no mapa da abertura nacional: pôr as forças de Macau ao serviço das necessidades do país. Naturalmente, para que um pivô alavanque de facto a abertura nacional, é preciso traduzir as vantagens institucionais em serviços que as empresas possam sentir, e consolidar um posicionamento diferenciado num lugar insubstituível — entre estes dois \"é preciso\" reside todo o trabalho necessário para levar o Terceiro Plano Quinquenal do projecto à realidade.",
            "O projecto está traçado; a chave está na execução. O \"amortecedor\" não nasce por si. Ao longo dos três momentos — antes, durante e depois — o Governo, o sector empresarial e o meio académico têm cada um os seus deveres.",
            "Antes, amortecer: digerir a incerteza antes da partida. Sugere-se que o Governo crie quanto antes um grupo de trabalho dedicado e um balcão único de serviços à internacionalização das empresas, integrando o direito, a contabilidade, a certificação e a arbitragem em língua portuguesa num \"pacote de serviços de internacionalização\" normalizado, para que as micro, pequenas e médias empresas, antes de levantar âncora, vejam com clareza os recifes da rota. É traduzir o património institucional de Macau em serviços tangíveis para a abertura de alto nível do país.",
            "Durante, dar suporte: sedimentar a experiência individual em património público. Sugere-se que o sector empresarial construa em conjunto um repositório de fornecedores certificados e uma base de conhecimento de casos, para que, num ecossistema em que \"os grandes levam os pequenos\", a experiência dos pioneiros sirva de alicerce aos que vêm depois — o buraco em que uma empresa caiu não deve apanhar uma segunda. É converter o custo de tentativa e erro de cada empresa na resiliência global do sistema de abertura nacional.",
            "Depois, fazer ressaltar: forjar a gestão de crises numa disciplina. Para as empresas que sofreram uma aterragem forçada, \"uma empresa, uma política\" e acompanhamento por especialistas; o meio académico deve tratar estes casos como verdadeira ciência — escrever mais relatórios úteis, formar mais estudantes capazes, acompanhar mais empresas no troço mais difícil do caminho. A coordenação do desenvolvimento e da segurança deve reflectir-se não só na concepção de topo do país, mas também em cada mola deste \"amortecedor\" de Macau.",
            "Um pivô não se proclama: aparafusa-se, parafuso a parafuso. E as mãos que apertam esses parafusos estão entre os jovens desta geração de Macau.",
            "O sistema de primazia do executivo deu a Macau a eficiência de concentrar forças para grandes empreendimentos; \"Um País, Dois Sistemas\" deu a Macau o dom de ligar a China e o Ocidente. O Presidente Xi Jinping exortou Macau a \"erguer-se alto e olhar longe, acolher todos os rios, avançar com determinação\". Esta exortação, trazida para o Terceiro Plano Quinquenal, significa ligar estreitamente o destino de Macau à abertura nacional, fazendo com que as vantagens institucionais de \"Um País, Dois Sistemas\" avancem com estabilidade ao serviço das necessidades do país. É a prática mais concreta do valor central de \"amar a pátria e amar Macau\" na nova era. O peso do plano não está nas entrelinhas das suas dez partes e trinta e seis capítulos, mas nos livros de contas de milhares de empresas. A oportunidade que a história deu a Macau há-de, no fim, medir-se pela possibilidade de aquele empresário, no seu escritório de madrugada, poder dormir descansado.",
            "Macau não precisa de se tornar o próximo Hong Kong ou Singapura. Oxalá daqui a cinco anos, cada empresário que a altas horas negoceia através de fusos horários tenha debaixo dos pés um \"amortecedor\" feito em Macau — eis a resposta mais simples e mais sólida de Macau à \"promoção mútua da circulação nacional e internacional\".",
        ],
    },
}

# 研究洞察 6 articles (titles/categories/excerpts per language, dates fixed)
insights = [oped_article,
    {"date": "2026-03-15", "category": {"zh-TW": "數字經濟", "zh-CN": "数字经济", "en": "Digital Economy", "pt": "Economia Digital"},
     "title": {"zh-TW": "澳門數字經濟發展趨勢", "zh-CN": "澳门数字经济发展趋势", "en": "Digital Economy Trends in Macao", "pt": "Tendências da Economia Digital em Macau"},
     "excerpt": {"zh-TW": "分析澳門特區數字化轉型的機遇與挑戰", "zh-CN": "分析澳门特区数字化转型的机遇与挑战", "en": "Analysis of digital transformation opportunities and challenges in Macao SAR", "pt": "Análise de oportunidades e desafios da transformação digital na RAE de Macau"}},
    {"date": "2026-03-10", "category": {"zh-TW": "區域合作", "zh-CN": "区域合作", "en": "Regional Cooperation", "pt": "Cooperação Regional"},
     "title": {"zh-TW": "大灣區融合發展策略", "zh-CN": "大湾区融合发展策略", "en": "Greater Bay Area Integration Strategies", "pt": "Estratégias de Integração da Grande Baía"},
     "excerpt": {"zh-TW": "提升澳門在大灣區角色的政策建議", "zh-CN": "提升澳门在大湾区角色的政策建议", "en": "Policy recommendations for enhancing Macao's role in the Greater Bay Area", "pt": "Recomendações políticas para fortalecer o papel de Macau na Grande Baía"}},
    {"date": "2026-03-05", "category": {"zh-TW": "可持續金融", "zh-CN": "可持续金融", "en": "Sustainable Finance", "pt": "Finanças Sustentáveis"},
     "title": {"zh-TW": "ESG投資機遇", "zh-CN": "ESG投资机遇", "en": "ESG Investment Opportunities", "pt": "Oportunidades de Investimento ESG"},
     "excerpt": {"zh-TW": "探索可持續投資趨勢與綠色金融倡議", "zh-CN": "探索可持续投资趋势与绿色金融倡议", "en": "Exploring sustainable investment trends and green finance initiatives", "pt": "Explorando tendências de investimento sustentável e iniciativas de finanças verdes"}},
    {"date": "2026-02-28", "category": {"zh-TW": "現代金融", "zh-CN": "现代金融", "en": "Modern Finance", "pt": "Finanças Modernas"},
     "title": {"zh-TW": "人民幣國際化進展", "zh-CN": "人民币国际化进展", "en": "RMB Internationalization Progress", "pt": "Progresso da Internacionalização do RMB"},
     "excerpt": {"zh-TW": "人民幣跨境使用與金融合作的最新進展", "zh-CN": "人民币跨境使用与金融合作的最新进展", "en": "Latest developments in cross-border RMB usage and financial cooperation", "pt": "Últimos desenvolvimentos no uso transfronteiriço do RMB e cooperação financeira"}},
    {"date": "2026-02-20", "category": {"zh-TW": "創新", "zh-CN": "创新", "en": "Innovation", "pt": "Inovação"},
     "title": {"zh-TW": "文化與科技創新", "zh-CN": "文化与科技创新", "en": "Culture and Technology Innovation", "pt": "Inovação em Cultura e Tecnologia"},
     "excerpt": {"zh-TW": "科技如何改變澳門文化產業", "zh-CN": "科技如何改变澳门文化产业", "en": "How technology is transforming Macao's cultural industries", "pt": "Como a tecnologia está transformando as indústrias culturais de Macau"}},
    {"date": "2026-02-15", "category": {"zh-TW": "政策研究", "zh-CN": "政策研究", "en": "Policy Research", "pt": "Pesquisa Política"},
     "title": {"zh-TW": "自由貿易港監管最佳實踐", "zh-CN": "自由贸易港监管最佳实践", "en": "Free Trade Port Regulation Best Practices", "pt": "Melhores Práticas de Regulação de Porto de Livre Comércio"},
     "excerpt": {"zh-TW": "海關監管框架的國際比較", "zh-CN": "海关监管框架的国际比较", "en": "International comparison of customs regulation frameworks", "pt": "Comparação internacional de estruturas de regulação aduaneira"}},
]

# 首頁三大重點領域卡片
focus_cards = [
    {"icon": "trending", "title": {"zh-TW": "現代金融", "zh-CN": "现代金融", "en": "Modern Finance", "pt": "Finanças Modernas"},
     "description": {"zh-TW": "推動金融科技創新與跨境金融合作", "zh-CN": "推动金融科技创新与跨境金融合作", "en": "Driving fintech innovation and cross-border financial cooperation", "pt": "Impulsionando inovação fintech e cooperação financeira transfronteiriça"}},
    {"icon": "globe", "title": {"zh-TW": "數字經濟", "zh-CN": "数字经济", "en": "Digital Economy", "pt": "Economia Digital"},
     "description": {"zh-TW": "探索人工智能、電子商務與數字化轉型", "zh-CN": "探索人工智能、电子商务与数字化转型", "en": "Exploring AI, e-commerce, and digital transformation", "pt": "Explorando IA, comércio eletrónico e transformação digital"}},
    {"icon": "users", "title": {"zh-TW": "大灣區合作", "zh-CN": "大湾区合作", "en": "Greater Bay Area Cooperation", "pt": "Cooperação da Grande Baía"},
     "description": {"zh-TW": "促進區域融合與跨境合作", "zh-CN": "促进区域融合与跨境合作", "en": "Promoting regional integration and cross-border cooperation", "pt": "Promovendo integração regional e cooperação transfronteiriça"}},
]

# 出版物封面圖對應
book_covers = {"university": "book-university.webp", "community": "book-community.webp",
               "youth": "book-youth.webp", "supplement": "book-supplement.webp"}

# 語言切換器顯示名稱
languages = [
    {"code": "zh-TW", "label": "繁體中文", "flag": "🇲🇴"},
    {"code": "zh-CN", "label": "简体中文", "flag": "🇨🇳"},
    {"code": "en", "label": "English", "flag": "🇬🇧"},
    {"code": "pt", "label": "Português", "flag": "🇵🇹"},
]

content = {
    "languages": languages,
    "default_lang": "zh-TW",
    "site_name": "澳門財經科技與教育發展學會",
    "site_name_en": "Macao Financial Technology and Education Development Association",
    "site_url": "https://mfteda.org",
    "email": "mfteda2020@163.com",
    "social": {"facebook": "#", "linkedin": "#", "twitter": "#"},
    "partners_href": {
        "partner1": "https://www.dsedt.gov.mo",
        "partner2": "https://www.ipim.gov.mo",
        "partner3": "http://www.iolaw.cssn.cn",
        "partner4": "https://www.bjql.org.cn",
        "partner5": "https://www.bnu.edu.cn",
        "partner6": "https://www.gzhu.edu.cn",
        "partner7": "https://www.mpu.edu.mo",
        "partner8": "https://www.usj.edu.mo",
        "partner9": "https://www.jisu.edu.cn",
        "partner10": "https://www.instagram.com/macau.hall.de.cultura/",
        "partner11": "#",
        "partner12": "https://www.facebook.com/MacauLiveAssociation/",
    },
    "i18n": i18n,
    "insights": insights,
    "focus_cards": focus_cards,
    "policies": policies,
    "book_covers": book_covers,
}

with open('content.json', 'w', encoding='utf-8') as f:
    json.dump(content, f, ensure_ascii=False, indent=2)
print('content.json written:', len(json.dumps(content, ensure_ascii=False)), 'chars')
